import re, os, json
os.chdir('/Users/portela/Documents/Programming/wedding/public/invitation/assets')
back=open('envelope-back.svg').read(); front=open('envelope-front.svg').read()
A='/invitation/assets'
TEX=('<pattern id="texPaper" patternUnits="userSpaceOnUse" width="150" height="150">'
     '<rect width="150" height="150" fill="#f3eee1"/>'
     '<image href="%s/paper-texture.png" width="150" height="150" preserveAspectRatio="xMidYMid slice"/></pattern>'
     '<pattern id="texLin" patternUnits="userSpaceOnUse" width="713" height="891">'
     '<image href="%s/lining.jpg" width="713" height="891" preserveAspectRatio="xMidYMid slice"/></pattern>')%(A,A)

def vbox(s): return re.search(r'viewBox="([^"]+)"',s).group(1)
def body(s): return re.sub(r'^.*?</defs>','',s,flags=re.S).replace('</svg>','')
def grads(s):  # everything in <defs> except the <style>
    d=re.search(r'<defs>(.*?)</defs>',s,re.S).group(1)
    return re.sub(r'<style>.*?</style>','',d,flags=re.S)
def classmap(s):  # uuid-class -> inline style decls, with recolors applied
    d=re.search(r'<defs>(.*?)</defs>',s,re.S).group(1)
    m={}
    for mm in re.finditer(r'\.([a-f0-9-]{36})\s*\{\s*([^}]*)\}', d):
        decl=mm.group(2).strip().rstrip(';')
        decl=re.sub(r'fill:\s*#fff\b','fill:url(#texPaper)',decl)
        decl=re.sub(r'fill:\s*rgba\(255,\s*255,\s*255[^)]*\)','fill:url(#texPaper)',decl)
        decl=re.sub(r'fill:\s*#cca500\b','fill:url(#texLin)',decl)
        decl=re.sub(r'fill:\s*#af9d30\b','fill:url(#texLin)',decl)
        m[mm.group(1)]=decl
    return m
def inline_classes(content, cm):
    def rep(mo):
        cls=mo.group(1); 
        return 'style="%s"'%cm.get(cls,'') if cls in cm else 'class="%s"'%cls
    return re.sub(r'class="([a-f0-9-]{36})"', rep, content)
def group(s,name):
    b=body(s); k=b.find('data-name="%s"'%name); gs=b.rfind('<g',0,k)
    i=b.find('>',k)+1; depth=1; j=i
    while depth>0:
        ng=b.find('<g',j); nc=b.find('</g>',j)
        if nc==-1: break
        if ng!=-1 and ng<nc: depth+=1; j=ng+2
        else: depth-=1; j=nc+4
    return b[gs:j]
def namespace(s, p):
    ids=sorted(set(re.findall(r'id="([^"]+)"',s)), key=len, reverse=True)
    for i in ids:
        s=s.replace('id="%s"'%i,'id="%s_%s"'%(p,i)).replace('url(#%s)'%i,'url(#%s_%s)'%(p,i)).replace('href="#%s"'%i,'href="#%s_%s"'%(p,i))
    return s

def layer(prefix, vb, src, content, yclip=None):
    cm=classmap(src); g=grads(src)
    content=inline_classes(content,cm)
    clip=''; cattr=''
    W=vb.split()[2]; H=vb.split()[3]
    if yclip=='top': clip='<clipPath id="yc"><rect x="0" y="0" width="%s" height="488"/></clipPath>'%W; cattr=' clip-path="url(#yc)"'
    elif yclip=='bot': clip='<clipPath id="yc"><rect x="0" y="488" width="%s" height="%f"/></clipPath>'%(W,float(H)-488); cattr=' clip-path="url(#yc)"'
    inner='<defs>%s%s%s</defs><g%s>%s</g>'%(g,TEX,clip,cattr,content)
    return namespace(inner, prefix)

L={}
L['back']  ={'vb':vbox(back),  'svg':layer('eb',vbox(back), back, body(back), 'bot')}
L['flapOuter']={'vb':vbox(back),'svg':layer('fo',vbox(back), back, body(back), 'top')}
L['liner'] ={'vb':vbox(front), 'svg':layer('el',vbox(front),front, group(front,'liner'),'bot')}
L['flapInner']={'vb':vbox(front),'svg':layer('fi',vbox(front),front, group(front,'liner'),'top')}
L['cover'] ={'vb':vbox(front), 'svg':layer('ec',vbox(front),front, group(front,'cover'), None)}
open('/Users/portela/Documents/Programming/wedding/src/envelope-layers.js','w').write(
  '// AUTO-GENERATED by scripts/gen-envelope-layers.py — inline SVG envelope layers\n'
  '// (vector, re-rasterised crisp at the camera zoom; textures referenced at full res)\n'
  'export const ENV_LAYERS = '+json.dumps(L)+';\n')
for k,v in L.items(): print('%-10s vb=%s  %dKB'%(k, v['vb'], len(v['svg'])//1024))
