// content.js — all guest-facing text, in English (en) and Brazilian Portuguese (pt).
// This is the file to edit when updating names, dates, descriptions, gift handles, etc.
export const I18N = {
  en: {
    code: 'en',
    nav: { inicio: 'Home', padrinhos: 'People', evento: 'Event', viagem: 'Travel', brazil: 'Brazil', brasilia: 'Brasília', presentes: 'Gifts', confirmar: 'RSVP' },
    hero: { eyebrow: 'We’re getting married · Brasília, Brazil', dateItalic: 'Tuesday, the twenty-ninth of December, two thousand twenty-six',
      chips: ['29 Dec 2026', '5 PM · Ceremony', 'Brasília, Brazil'] },
    couple: { eyebrow: 'The couple', title: 'Welcome',
      p1: 'We’re Anna and Matheus — and after years of building a life together, we’re finally throwing the party!',
      p2: 'We couldn’t be happier that you’ll be there to celebrate with us. This little site has everything you need to plan the trip and join us on the day.' },
    party: { eyebrow: 'Those who walk with us', title: 'Our People', namePh: 'Name Surname',
      intro: 'In Brazil, the couple is surrounded by padrinhos and madrinhas — literally the godparents of the wedding. They’re the closest family and friends who shaped our story and will stand beside us at the altar: the equivalent of groomsmen and bridesmaids elsewhere.',
      groups: [
        { group: 'Honour Attendants', people: [['Name Surname', 'Maid of Honour'], ['Name Surname', 'Best Man']] },
        { group: 'Bridesmaids', people: [['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid']] },
        { group: 'Groomsmen', people: [['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman']] },
      ],
      foot: 'There’s nothing you need to do — but if you spot a group in matching colours on the day, now you know who they are. (Names above are placeholders — the final list is coming soon.)' },
    event: { eyebrow: 'The celebration', title: 'The Event',
      intro: 'Everything happens in one place: Espaço Renascença, a green venue just minutes from central Brasília. The ceremony and the party are steps apart, so plan to spend the whole evening with us.',
      ceremony: { tag: 'Ceremony', time: '5 PM', desc: 'We’ll marry outdoors, in the beautiful open garden.' },
      reception: { tag: 'Reception', time: '6 PM', desc: 'Right next door for dinner, toasts, and dancing.' },
      rows: [
        ['Location', 'Espaço Renascença\nSetor de Mansões Park Way Quadra 13 Conj. 01 Lote 06\nBrasília, DF, Brazil'],
        ['Dress code', 'Formal — long dresses and suits. Open-air garden, so choose light, breathable fabrics.'],
        ['Weather', 'Late December is hot and humid, with a chance of a quick shower — a light layer is a sensible bet.'],
      ],
      mapBtn: 'View on map' },
    travel: { eyebrow: 'For our guests from abroad', title: 'Travel',
      intro: 'Everything you need to plan the trip to Brasília — getting here, getting around, and the practical bits.',
      cards: [
        ['Getting to Brasília', 'Fly into Brasília — Juscelino Kubitschek International Airport (BSB).', [
          'Direct international: TAP from Lisbon, GOL from Miami & Orlando, Copa from Panama City.',
          'From elsewhere, connect via São Paulo (GRU) or Rio de Janeiro (GIG). Allow at least a 2-hour layover to clear customs, immigration, and change terminals without stress.',
          'Pro tip: Brasília has direct flights across the whole country — a great chance to explore Brazil on the domestic carriers (LATAM, GOL, and Azul).',
        ]],
        ['Getting around', 'Brasília was designed for cars, so distances between sights are large.', [
          'We recommend Uber: reliable, inexpensive, and the safest way to move. Official taxis are also a good option (except in Rio de Janeiro).',
          'Renting a car is possible with an International Driving Permit; parking is plentiful and free in most places.',
          'Public transit is not widely available: there are buses and a limited metro service.',
        ]],
        ['Where to stay', 'Most hotels sit close together in the central Hotel Sectors or by Lake Paranoá. Our recommendations:', [
          'Lake Paranoá: Royal Tulip · Brasília Palace · Golden Tulip · Lake Side Apart Hotel.',
          'North Hotel Sector: B Hotel · Mercure Líder · Grand Mercure · Nobile Suites Monumental · Windsor Brasília.',
          'Pro tip: avoid walking around the hotel sector at night — take an Uber from the lobby. Booking.com is handy for managing reservations.',
        ]],
        ['Money & currency', 'The currency is the Brazilian Real (R$ / BRL). Roughly R$5 ≈ US$1, or R$6 ≈ €1 (rates vary).', [
          'Cards and contactless are universally accepted — you’ll rarely need cash. Visa and Mastercard work everywhere; Amex and Discover often don’t.',
          'If a card machine offers to convert the price, always choose to pay in Brazilian Real and let your bank do the conversion.',
          'There’s no tipping culture, except at restaurants, where a 10% service charge is already included in the bill.',
        ]],
        ['Visa & entry', 'Requirements changed recently — please check early.', [
          'US, Canada, China & Australia: e-Visa required (about US$80.90). Apply at the official portal [brazil.vfsevisa.com](https://brazil.vfsevisa.com) at least 3 weeks ahead.',
          'UK & EU: no visa required for tourism up to 90 days.',
          'Passport valid 6+ months. Always confirm with official government sources.',
        ]],
        ['When to book', 'Late December is peak Brazilian summer and holiday season, so plan ahead.', [
          'Flights: book 4–6 months out for the best fares.',
          'Hotels: reserve early for touristic cities (like Rio or Florianópolis), especially around New Year.',
        ]],
      ] },
    brazil: { eyebrow: 'Your first time in Brazil', title: 'Brazil', photo: 'brazil · from coast to cerrado',
      intro: 'Brazil is a _massive_ country with deep history and rich culture. Here’s our first-timer’s guide to making the most of your visit.',
      watch: { title: 'Watch before you come',
        lead: 'A few short videos are a lovely way to arrive already in the mood. If it’s your first time in Brazil, these set the scene:',
        videos: [
          ['Dots on a Map — Brasília: Brazil’s Bizarre Capital', 'https://www.youtube.com/watch?v=HbS_nmFAddk'],
          ['Dots on a Map — Rio de Janeiro', 'https://www.youtube.com/watch?v=3FioV9MwBOA'],
          ['Dots on a Map — Salvador', 'https://www.youtube.com/watch?v=53qpaG8Q2OA'],
          ['Dots on a Map — Florianópolis', 'https://www.youtube.com/watch?v=iS022g0kT9A'],
          ['Dots on a Map — São Paulo', 'https://www.youtube.com/watch?v=tvaXa7HS7ow'],
          ['Phrases you need before you travel to Brazil', 'https://www.youtube.com/watch?v=eMsDho6otek'],
          ['Best Places to Visit in Brazil', 'https://www.youtube.com/watch?v=q7zdJ-nMrlE'],
          ['What Tourists Should Know about Brazil', 'https://www.youtube.com/watch?v=NXtnHGvhIQg'],
          ['Brazil in 2 Weeks', 'https://www.youtube.com/watch?v=sremk7jo15k'],
        ] },
      info: [
        { icon: 'wifi', title: 'Staying connected (eSIM)', lead: 'Getting online in Brazil is easy and cheap:', items: [
          ['The simplest option', 'is a travel eSIM you buy before you fly. Airalo, Holafly, or Saily activate the moment you land — no swapping your physical SIM or paying inflated roaming.'],
          ['A local SIM', 'from Vivo, Claro, or TIM is cheaper still, but usually needs a Brazilian CPF (tax ID), which most visitors don’t have.'],
          ['Coverage', 'is excellent in every major city, and Wi-Fi is widespread in hotels, restaurants, and malls — just ask the staff for the password.'],
          ['Pro tip:', 'mobile data is essential here — you’ll need it for Uber, maps, and translation.'],
        ] },
        { icon: 'chat', title: 'Language', lead: 'The language is Portuguese — its own language, distinct from Spanish (though Spanish helps you catch the gist).', items: [
          ['English', 'is not widely spoken outside hotels and tourist spots, so don’t rely on it for everyday situations.'],
          ['Google Translate', 'goes a long way — its camera and conversation modes are lifesavers. Download the offline Portuguese pack just in case.'],
          ['Don’t be shy:', 'Brazilians are famously warm and will go out of their way to help. A smiling “obrigado / obrigada” (thank you) opens every door.'],
        ] },
        { icon: 'money', title: 'Cost of living', lead: 'For most international visitors, Brazil is great value:', items: [
          ['Flights', 'are the big-ticket item — international fares have climbed with oil prices, so book as early as you can.'],
          ['Everything else', '— food, transport, and entertainment — is noticeably cheaper than in the US or Europe. A great meal or a long Uber ride won’t break the bank.'],
          ['Day to day', 'is simple: cards are accepted everywhere and the exchange rate is favourable (roughly R$5 ≈ US$1).'],
        ] },
        { icon: 'sun', title: 'Weather', lead: 'Pack for heat. Late December is high summer in Brazil — if you’re escaping a northern winter, the contrast will be dramatic.', items: [
          ['Brasília & the south/southeast:', 'warm, humid, and in the rainy season — bright days broken by short, heavy afternoon showers. It’s common to just wait the rain out.'],
          ['The northeast:', 'hot and noticeably drier — perfect beach weather.'],
          ['The north (Amazon):', 'hot and humid year-round, with little seasonal change.'],
          ['Everywhere:', 'sunscreen, a hat, light clothes, and a refillable water bottle are your friends.'],
        ] },
        { icon: 'shield', title: 'Staying safe', lead: 'Brazil is wonderfully welcoming, but a little street sense goes a long way if you’re coming from a much safer country:', items: [
          ['Keep valuables low-key.', 'Don’t flash jewellery, watches, or your phone on the street — use your phone inside shops or restaurants.'],
          ['Mind where you go.', 'Stick to busy, well-lit, touristy areas and avoid empty streets. Ask your hotel which neighbourhoods to skip, and **never** visit favelas.'],
          ['Split your essentials.', 'Carry a copy of your passport’s photo page and leave the original at the hotel; bring two cards and leave one behind.'],
          ['Watch your belongings.', 'Don’t leave bags, phones, or cameras unattended — on the beach, at a table, or anywhere else.'],
        ], foot: 'None of this should make you anxious — reach out to us if you have any questions or concerns!' },
      ],
      biomes: { title: 'Brazil’s biomes', lead: 'Brazil is continental in scale, and the landscape changes completely from one region to the next. There are six great biomes:', items: [
        { name: 'Amazônia', desc: 'The world’s largest rainforest: dense, wet, and teeming with life.', img: '/images/biome-amazonia.png' },
        { name: 'Mata Atlântica', desc: 'The lush Atlantic Forest along the coast, hugging cities like Rio and São Paulo.', img: '/images/biome-mata-atlantica.png' },
        { name: 'Cerrado', desc: 'The tropical savanna around Brasília: twisted trees, vast skies, surprising biodiversity.', img: '/images/biome-cerrado.png' },
        { name: 'Pantanal', desc: 'The planet’s largest tropical wetland, and the best place in Brazil to spot wildlife.', img: '/images/biome-pantanal.png' },
        { name: 'Caatinga', desc: 'The semi-arid scrubland of the northeast, found nowhere else on earth.', img: '/images/biome-caatinga.png' },
        { name: 'Pampas', desc: 'The rolling grasslands of the far south, gaúcho country.', img: '/images/biome-pampas.png' },
      ] },
      food: { title: 'Food', lead: 'Come hungry. Brazilian cooking is generous, regional, and made for sharing:', foot: 'Brazil has a surprisingly large repertoire of gluten-free options.', items: [
        { name: 'Churrasco', desc: 'Brazilian barbecue, endless cuts of grilled meat.', img: '/images/food-churrasco.png' },
        { name: 'Feijoada', desc: 'The national dish: a rich black-bean and pork stew, best over a long, lazy lunch with cold beer and live music.', img: '/images/food-feijoada.png' },
        { name: 'Farofa', desc: 'Toasted cassava flour, the crunchy companion to almost everything.', img: '/images/food-farofa.png' },
        { name: 'Moqueca', desc: 'A fragrant fish stew with coconut milk, tomato, and palm oil.', img: '/images/food-moqueca.png' },
        { name: 'Acarajé', desc: 'Bahian street food of Nigerian origin, packed with flavour.', img: '/images/food-acaraje.png' },
        { name: 'Pão de queijo', desc: 'Warm, chewy cheese bread; impossible to eat just one.', img: '/images/food-pao-de-queijo.png' },
        { name: 'Coxinha', desc: 'Teardrop-shaped fried chicken croquettes, the king of snacks.', img: '/images/food-coxinha.png' },
        { name: 'Açaí', desc: 'Frozen Amazonian berry bowls, served thick and cold.', img: '/images/food-acai.png' },
        { name: 'Tapioca', desc: 'Cassava crêpes, sweet or savoury.', img: '/images/food-tapioca.png' },
        { name: 'Brigadeiro', desc: 'Chocolate fudge balls, the classic sweet.', img: '/images/food-brigadeiro.png' },
        { name: 'Pudim', desc: 'Brazilian-style caramel flan.', img: '/images/food-pudim.png' },
        { name: 'Caipirinha', desc: 'The national cocktail: cachaça, lime, sugar, and ice.', img: '/images/food-caipirinha.png' },
      ] },
      holidays: { title: 'Christmas & New Year’s Eve', lead: 'Our wedding falls right between Brazil’s two biggest holidays, so it helps to know how the country celebrates:', items: [
        { name: 'Christmas (24–25 Dec)', desc: 'A warm, family affair — the main celebration is dinner on the night of the 24th, and most shops and restaurants close on the 24th and 25th.', img: '/images/holiday-christmas.png' },
        { name: 'New Year’s Eve (Réveillon)', desc: 'A national party, best by the sea: wear all white and jump seven waves at midnight. The biggest celebrations are in Rio, Florianópolis, Salvador, and Recife. Hotels sell out early, so book ahead.', img: '/images/holiday-new-years-eve.png' },
      ] },
      music: { title: 'Music & dance', lead: 'Music is everywhere in Brazil, and every region has its own beat:', foot: 'Don’t worry if you can’t dance — by the end of the night, you will.', items: [
        { name: 'Samba', desc: 'The heartbeat of Rio, and of Carnival.', img: '/images/music-samba.jpg' },
        { name: 'Forró & baião', desc: 'Accordion-driven rhythms from the northeast, made for partner dancing.', img: '/images/music-forro.png' },
        { name: 'Olodum & axé', desc: 'High-energy, percursive rhythms from Bahia.', img: '/images/music-olodum.png' },
        { name: 'Sertanejo', desc: 'Brazil’s country music, the sound of the interior.', img: '/images/music-sertanejo.png' },
        { name: 'Funk', desc: 'Urban music to dance in Rio de Janeiro and São Paulo.', img: '/images/music-funk.png' },
      ] },
      trip: { title: 'Make it a trip',
        lead: 'Brasília sits at the centre of the country, with quick connections to the coast and beyond. If you’re flying this far, it’s worth seeing more of Brazil.',
        items: [
          { name: 'Rio de Janeiro', desc: 'Beaches, Christ the Redeemer, and Sugarloaf — Brazil’s postcard city.', img: '/images/rio de janeiro.png' },
          { name: 'Foz do Iguaçu', desc: 'One of the world’s great waterfalls, on the Argentine border.', img: '/images/foz do iguacu.png' },
          { name: 'Salvador', desc: 'The Afro-Brazilian heart of Bahia: colour, history, and rhythm.', img: '/images/salvador.png' },
          { name: 'Amazon Rainforest', desc: 'River journeys and rainforest lodges, usually via Manaus.', img: '/images/amazonia.png' },
          { name: 'Fernando de Noronha', desc: 'A protected archipelago with Brazil’s most beautiful beaches.', img: '/images/fernando de noronha.png' },
          { name: 'Porto de Galinhas', desc: 'Warm natural pools and reef-sheltered beaches in Pernambuco.', img: '/images/porto de galinhas.png' },
          { name: 'Chapada dos Veadeiros', desc: 'The largest national park in the Cerrado biome — pretty close to Brasília.', img: '/images/chapada dos veadeiros.png' },
          { name: 'Lençóis Maranhenses', desc: 'Endless white dunes dotted with rain-fed lagoons.', img: '/images/lencois maranhenses.png' },
          { name: 'Búzios, Cabo Frio & Arraial do Cabo', desc: 'Chic beach towns and turquoise water near Rio.', img: '/images/buzios.png' },
          { name: 'Paraty', desc: 'A colonial port town between rainforest and sea.', img: '/images/paraty.png' },
          { name: 'São Paulo', desc: 'Brazil’s biggest city: world-class food, art, and nightlife.', img: '/images/sao paulo.png' },
        ] } },
    brasilia: { eyebrow: 'The city you’re flying into', title: 'Brasília', photo: 'brasília · modernist skyline',
      whatTitle: 'A capital like no other',
      intro: 'Brazil’s capital was built from open savanna and inaugurated in 1960 — a modernist city imagined by urban planner Lúcio Costa and architect Oscar Niemeyer, laid out in the shape of an aeroplane. Its sweeping concrete-and-glass landmarks earned it UNESCO World Heritage status, and it’s unlike anywhere else on earth.',
      seeLabel: 'Things to see & do',
      sights: [
        { name: 'Cathedral of Brasília', desc: 'Niemeyer’s crown of glass and light.', img: '' },
        { name: 'National Congress', desc: 'The twin towers and twin domes on the Esplanade.', img: '' },
        { name: 'Palácio do Planalto', desc: 'The president’s office, all glass and curves.', img: '' },
        { name: 'Supreme Court (STF)', desc: 'Brazil’s highest court, on the Praça dos Três Poderes.', img: '' },
        { name: 'Praça dos Três Poderes', desc: 'The civic heart where the three branches meet.', img: '' },
        { name: 'JK Memorial', desc: 'Tomb and museum of the city’s founder, Juscelino Kubitschek.', img: '' },
        { name: 'Itamaraty Palace', desc: 'The foreign ministry, with water gardens and arches.', img: '' },
        { name: 'Pontão do Lago Sul', desc: 'Lakeside boardwalk of bars and restaurants — great at sunset.', img: '' },
        { name: 'Ponte JK', desc: 'The graceful triple-arch bridge over Lake Paranoá.', img: '' },
        { name: 'TV Tower', desc: 'A free observation deck with sweeping city views.', img: '' },
        { name: 'Digital TV Tower', desc: 'Niemeyer’s “flower” tower with a panoramic lookout.', img: '' },
        { name: 'Santuário Dom Bosco', desc: 'A chapel washed in deep-blue stained-glass light.', img: '' },
        { name: 'Parque da Cidade', desc: 'A vast urban park for walking, cycling, and picnics.', img: '' },
        { name: 'Praça dos Cristais', desc: 'Sculptural concrete prisms set in green lawns.', img: '' },
        { name: 'Lago Paranoá', desc: 'The city’s lake — sunset cruises, kayaking, and stand-up paddle.', img: '' },
        { name: 'Chapada dos Veadeiros', desc: 'Waterfalls and canyons ~3h away — a cerrado day trip.', img: '' },
        { name: 'Pirenópolis', desc: 'A colonial mountain town with waterfalls, ~2h from the city.', img: '' },
      ] },
    rsvp: { eyebrow: 'RSVP · please reply by September 2026', title: 'Will you come?',
      intro: 'We’re keeping the celebration intimate. Let us know if you can make it — one response per invitation is perfect.',
      notes: [
        ['Adults only', 'As much as we love the little ones, this will be a grown-ups’ evening.'],
        ['No plus-ones', 'Your invitation is for the names printed on it. If you’re unsure whether a guest is included, just ask us.'],
        ['Reply by September 2026', 'So we can confirm final numbers with the venue.'],
      ],
      name: 'Full name', namePh: 'Your name', email: 'Email', emailPh: 'you@email.com',
      attending: 'Attending?', attendingPh: 'Joyfully yes / Sadly no', guests: 'Guests',
      note: 'A note or song request', notePh: 'Optional…', submit: 'Send RSVP',
      foot: 'We know travelling here is a real commitment, and we don’t take it for granted. Thank you for making the effort to celebrate with us!' },
    registry: { eyebrow: 'Gift list', title: 'Gifts',
      intro: 'Your presence — especially for those flying a long way — is genuinely the only gift we’re hoping for. Since we live abroad, please don’t worry about bringing anything physical. If you’d still like to help with our future honeymoon, a contribution is warmly welcomed.',
      ways: [['Pix', 'For guests in Brazil', 'Our PIX key:', '[ coming soon ]'], ['Venmo', 'For guests in the US', 'Find us at:', '[ coming soon ]'], ['Wise', 'For international guests', 'Send in your currency:', '[ coming soon ]']],
      note: 'The handles above will be added before launch — and no gift is ever expected. Truly.' },
    footer: { dateLine: '29 · 12 · 2026 — Brasília, Brazil' },
  },

  pt: {
    code: 'pt',
    nav: { inicio: 'Início', padrinhos: 'Padrinhos', evento: 'Evento', viagem: 'Viagem', brazil: 'Brasil', brasilia: 'Brasília', presentes: 'Presentes', confirmar: 'Confirmar' },
    hero: { eyebrow: 'Nós vamos casar · Brasília, Brasil', dateItalic: 'terça-feira, vinte e nove de dezembro de dois mil e vinte e seis',
      chips: ['29 Dez 2026', '17h · Cerimônia', 'Brasília, Brasil'] },
    couple: { eyebrow: 'O casal', title: 'Bem-vindos',
      p1: 'Somos Anna e Matheus — e depois de anos construindo uma vida juntos, vamos finalmente fazer a festa!',
      p2: 'Não poderíamos estar mais felizes em ter você conosco para celebrar. Este site reúne tudo o que você precisa para planejar a viagem e participar do nosso grande dia.' },
    party: { eyebrow: 'Quem caminha conosco', title: 'Padrinhos', namePh: 'Nome Sobrenome',
      intro: 'No Brasil, os noivos são cercados por padrinhos e madrinhas — as pessoas mais próximas, que fizeram parte da nossa história e estarão ao nosso lado no altar.',
      groups: [
        { group: 'Padrinhos de Honra', people: [['Nome Sobrenome', 'Madrinha de Honra'], ['Nome Sobrenome', 'Padrinho de Honra']] },
        { group: 'Madrinhas', people: [['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha']] },
        { group: 'Padrinhos', people: [['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho']] },
      ],
      foot: 'Você não precisa fazer nada — mas, se vir um grupo com as mesmas cores no dia, agora você sabe quem são. (Os nomes acima são exemplos — a lista final vem em breve.)' },
    event: { eyebrow: 'A celebração', title: 'Evento',
      intro: 'Tudo acontece em um só lugar: o Espaço Renascença, um espaço verde a poucos minutos do centro de Brasília. A cerimônia e a festa são lado a lado, então reserve a noite toda para celebrar conosco.',
      ceremony: { tag: 'Cerimônia', time: '17h', desc: 'Vamos nos casar ao ar livre, no lindo jardim aberto.' },
      reception: { tag: 'Recepção', time: '18h', desc: 'Logo ao lado, com jantar, brindes e muita dança.' },
      rows: [
        ['Local', 'Espaço Renascença\nSetor de Mansões Park Way Quadra 13 Conj. 01 Lote 06\nBrasília, DF, Brasil'],
        ['Traje', 'Formal — vestidos longos e ternos. Jardim ao ar livre, então prefira tecidos leves e frescos.'],
        ['Clima', 'O fim de dezembro é quente e úmido, com chance de chuva rápida — leve um casaco leve por garantia.'],
      ],
      mapBtn: 'Ver no mapa' },
    travel: { eyebrow: 'Para nossos convidados de fora', title: 'Viagem',
      intro: 'Tudo o que você precisa para planejar a viagem a Brasília — como chegar, como se locomover e os detalhes práticos.',
      cards: [
        ['Como chegar a Brasília', 'Voe até o Aeroporto Internacional de Brasília — Juscelino Kubitschek (BSB).', [
          'Voos diretos internacionais: TAP de Lisboa, GOL de Miami e Orlando, Copa do Panamá.',
          'De outros lugares, conecte por São Paulo (GRU) ou Rio de Janeiro (GIG). Reserve ao menos 2h de conexão para passar pela imigração e trocar de terminal com tranquilidade.',
          'Dica: Brasília tem voos diretos para todo o país — uma ótima chance de explorar o Brasil pelas companhias domésticas (LATAM, GOL e Azul).',
        ]],
        ['Como se locomover', 'Brasília foi feita para carros, então as distâncias entre os pontos são grandes.', [
          'Recomendamos o Uber: confiável, barato e o jeito mais seguro de circular. Táxis oficiais também são uma boa opção (exceto no Rio de Janeiro).',
          'Alugar carro é possível com Permissão Internacional para Dirigir; estacionamento é abundante e gratuito na maioria dos lugares.',
          'O transporte público não é amplamente disponível: há ônibus e um metrô de cobertura limitada.',
        ]],
        ['Onde ficar', 'A maioria dos hotéis fica próxima nos Setores Hoteleiros centrais ou à beira do Lago Paranoá. Nossas recomendações:', [
          'Lago Paranoá: Royal Tulip · Brasília Palace · Golden Tulip · Lake Side Apart Hotel.',
          'Setor Hoteleiro Norte: B Hotel · Mercure Líder · Grand Mercure · Nobile Suites Monumental · Windsor Brasília.',
          'Dica: evite andar a pé pelo setor hoteleiro à noite — pegue um Uber na portaria. O Booking.com facilita gerenciar as reservas.',
        ]],
        ['Dinheiro & moeda', 'A moeda é o Real (R$ / BRL). Aproximadamente R$5 ≈ US$1, ou R$6 ≈ €1 (varia).', [
          'Cartões e aproximação são aceitos em todo lugar — dificilmente você vai precisar de dinheiro. Visa e Mastercard funcionam em qualquer lugar; Amex e Discover, muitas vezes não.',
          'Se a maquininha oferecer conversão de moeda, escolha sempre pagar em Real e deixe seu banco fazer a conversão.',
          'Não há cultura de gorjeta, exceto em restaurantes, onde os 10% de serviço já vêm na conta.',
        ]],
        ['Visto & entrada', 'As regras mudaram recentemente — verifique com antecedência.', [
          'EUA, Canadá, China e Austrália: e-Visa obrigatório (cerca de US$80,90). Solicite no portal oficial [brazil.vfsevisa.com](https://brazil.vfsevisa.com) com pelo menos 3 semanas de antecedência.',
          'Reino Unido e UE: sem visto para turismo até 90 dias.',
          'Passaporte válido por 6+ meses. Sempre confirme em fontes oficiais do governo.',
        ]],
        ['Quando reservar', 'O fim de dezembro é alta temporada de verão e festas, então planeje com antecedência.', [
          'Voos: reserve com 4–6 meses para os melhores preços.',
          'Hotéis: reserve cedo para cidades turísticas (como Rio ou Florianópolis), especialmente perto do Ano Novo.',
        ]],
      ] },
    brazil: { eyebrow: 'Sua primeira vez no Brasil', title: 'Brasil', photo: 'brasil · do litoral ao cerrado',
      intro: 'O Brasil é um país _imenso_, de história profunda e cultura rica. Este é o nosso guia para quem visita o país pela primeira vez.',
      watch: { title: 'Assista antes de vir',
        lead: 'Alguns vídeos curtos são um jeito ótimo de chegar já no clima. Se é a sua primeira vez no Brasil, estes ajudam a preparar o terreno:',
        videos: [
          ['Dots on a Map — Brasília: a capital bizarra do Brasil', 'https://www.youtube.com/watch?v=HbS_nmFAddk'],
          ['Dots on a Map — Rio de Janeiro', 'https://www.youtube.com/watch?v=3FioV9MwBOA'],
          ['Dots on a Map — Salvador', 'https://www.youtube.com/watch?v=53qpaG8Q2OA'],
          ['Dots on a Map — Florianópolis', 'https://www.youtube.com/watch?v=iS022g0kT9A'],
          ['Dots on a Map — São Paulo', 'https://www.youtube.com/watch?v=tvaXa7HS7ow'],
          ['Frases que você precisa antes de viajar ao Brasil', 'https://www.youtube.com/watch?v=eMsDho6otek'],
          ['Melhores lugares para visitar no Brasil', 'https://www.youtube.com/watch?v=q7zdJ-nMrlE'],
          ['O que turistas devem saber sobre o Brasil', 'https://www.youtube.com/watch?v=NXtnHGvhIQg'],
          ['Brasil em 2 semanas', 'https://www.youtube.com/watch?v=sremk7jo15k'],
        ] },
      info: [
        { icon: 'wifi', title: 'Internet (eSIM)', lead: 'Ficar online no Brasil é fácil e barato:', items: [
          ['O mais simples', 'é um eSIM de viagem comprado antes de embarcar. Airalo, Holafly ou Saily ativam assim que você pousa — sem trocar o chip físico nem pagar roaming caro.'],
          ['Um chip local', 'da Vivo, Claro ou TIM é ainda mais barato, mas geralmente exige um CPF, que a maioria dos visitantes não tem.'],
          ['A cobertura', 'é excelente em todas as grandes cidades, e o Wi-Fi é comum em hotéis, restaurantes e shoppings — é só pedir a senha.'],
          ['Dica:', 'dados móveis são essenciais aqui — você vai precisar para Uber, mapas e tradução.'],
        ] },
        { icon: 'chat', title: 'Idioma', lead: 'O idioma é o português — uma língua própria, diferente do espanhol (embora o espanhol ajude a entender o básico).', items: [
          ['O inglês', 'não é amplamente falado fora de hotéis e pontos turísticos, então não conte com ele no dia a dia.'],
          ['O Google Tradutor', 'ajuda muito — os modos câmera e conversa são salvadores. Baixe o pacote de português offline por garantia.'],
          ['Não tenha vergonha:', 'os brasileiros são famosos pela simpatia e fazem questão de ajudar. Um “obrigado / obrigada” com um sorriso abre todas as portas.'],
        ] },
        { icon: 'money', title: 'Custo de vida', lead: 'Para a maioria dos visitantes internacionais, o Brasil tem ótimo custo-benefício:', items: [
          ['As passagens aéreas', 'são o maior gasto — os preços internacionais subiram com o petróleo, então reserve o quanto antes.'],
          ['O resto', '— comida, transporte e lazer — é bem mais barato que nos EUA ou na Europa. Uma boa refeição ou um Uber longo não pesam no bolso.'],
          ['O dia a dia', 'é simples: cartões são aceitos em todo lugar e o câmbio é favorável (cerca de R$5 ≈ US$1).'],
        ] },
        { icon: 'sun', title: 'Clima', lead: 'Prepare-se para o calor. O fim de dezembro é pleno verão no Brasil — para quem foge do inverno do norte, o contraste é grande.', items: [
          ['Brasília e o Sul/Sudeste:', 'quente, úmido e em plena estação chuvosa — dias claros cortados por pancadas rápidas e fortes à tarde. É comum simplesmente esperar a chuva passar.'],
          ['O Nordeste:', 'quente e bem mais seco — clima perfeito de praia.'],
          ['O Norte (Amazônia):', 'quente e úmido o ano todo, com pouca variação.'],
          ['Em todo lugar:', 'protetor solar, chapéu, roupas leves e uma garrafa de água são seus melhores amigos.'],
        ] },
        { icon: 'shield', title: 'Segurança', lead: 'O Brasil é muito acolhedor, mas um pouco de atenção ajuda para quem vem de países bem mais seguros:', items: [
          ['Não chame atenção.', 'Evite exibir joias, relógios ou o celular na rua — use o telefone dentro de lojas ou restaurantes.'],
          ['Cuidado com os lugares.', 'Prefira áreas movimentadas, iluminadas e turísticas, e evite ruas vazias. Pergunte ao hotel quais bairros evitar, e **nunca** visite favelas.'],
          ['Separe o essencial.', 'Leve uma cópia da página de foto do passaporte e deixe o original no hotel; leve dois cartões e deixe um guardado.'],
          ['Fique de olho nos seus pertences.', 'Não deixe bolsas, celulares ou câmeras sem atenção — na praia, na mesa, em qualquer lugar.'],
        ], foot: 'Nada disso deve te deixar ansioso — fale com a gente se tiver qualquer dúvida ou preocupação!' },
      ],
      biomes: { title: 'Os biomas do Brasil', lead: 'O Brasil é de escala continental, e a paisagem muda completamente de uma região para outra. São seis grandes biomas:', items: [
        { name: 'Amazônia', desc: 'A maior floresta tropical do mundo: densa, úmida e cheia de vida.', img: '/images/biome-amazonia.png' },
        { name: 'Mata Atlântica', desc: 'A floresta exuberante do litoral, que abraça cidades como Rio e São Paulo.', img: '/images/biome-mata-atlantica.png' },
        { name: 'Cerrado', desc: 'A savana tropical ao redor de Brasília: árvores retorcidas, céus enormes e biodiversidade surpreendente.', img: '/images/biome-cerrado.png' },
        { name: 'Pantanal', desc: 'A maior área úmida tropical do planeta, e o melhor lugar do Brasil para ver animais.', img: '/images/biome-pantanal.png' },
        { name: 'Caatinga', desc: 'O sertão semiárido do Nordeste, que não existe em nenhum outro lugar do mundo.', img: '/images/biome-caatinga.png' },
        { name: 'Pampas', desc: 'Os campos do extremo Sul, terra dos gaúchos.', img: '/images/biome-pampas.png' },
      ] },
      food: { title: 'Comida', lead: 'Venha com fome. A cozinha brasileira é generosa, regional e feita para compartilhar:', foot: 'O Brasil tem um repertório surpreendentemente grande de opções sem glúten.', items: [
        { name: 'Churrasco', desc: 'A brasa brasileira, com cortes de carne sem fim.', img: '/images/food-churrasco.png' },
        { name: 'Feijoada', desc: 'O prato nacional: um ensopado encorpado de feijão-preto e porco, melhor num almoço longo e tranquilo, com cerveja gelada e música ao vivo.', img: '/images/food-feijoada.png' },
        { name: 'Farofa', desc: 'Farinha de mandioca torrada, a companhia crocante de quase tudo.', img: '/images/food-farofa.png' },
        { name: 'Moqueca', desc: 'Um ensopado de peixe perfumado com leite de coco, tomate e azeite de dendê.', img: '/images/food-moqueca.png' },
        { name: 'Acarajé', desc: 'Comida de rua baiana de origem nigeriana, cheia de sabor.', img: '/images/food-acaraje.png' },
        { name: 'Pão de queijo', desc: 'Quentinho e elástico; impossível comer só um.', img: '/images/food-pao-de-queijo.png' },
        { name: 'Coxinha', desc: 'O salgado em formato de gota, rei dos petiscos.', img: '/images/food-coxinha.png' },
        { name: 'Açaí', desc: 'A tigela gelada da fruta amazônica, servida bem grossa.', img: '/images/food-acai.png' },
        { name: 'Tapioca', desc: 'Crepes de mandioca, doces ou salgados.', img: '/images/food-tapioca.png' },
        { name: 'Brigadeiro', desc: 'O doce clássico de qualquer festa.', img: '/images/food-brigadeiro.png' },
        { name: 'Pudim', desc: 'Flan no melhor estilo brasileiro.', img: '/images/food-pudim.png' },
        { name: 'Caipirinha', desc: 'O coquetel nacional: cachaça, limão, açúcar e gelo.', img: '/images/food-caipirinha.png' },
      ] },
      holidays: { title: 'Natal & Réveillon', lead: 'Nosso casamento cai bem entre os dois maiores feriados do Brasil, então vale saber como o país comemora:', items: [
        { name: 'Natal (24–25 de dez)', desc: 'Uma celebração familiar e calorosa — a comemoração principal é a ceia na noite do dia 24, e a maioria das lojas e restaurantes fecha nos dias 24 e 25.', img: '/images/holiday-christmas.png' },
        { name: 'Réveillon (Ano Novo)', desc: 'Uma festa nacional, melhor à beira-mar: vista branco e pule sete ondas à meia-noite. As maiores festas são no Rio, em Florianópolis, Salvador e Recife. Os hotéis esgotam cedo, então reserve com antecedência.', img: '/images/holiday-new-years-eve.png' },
      ] },
      music: { title: 'Música & dança', lead: 'A música está em todo lugar no Brasil, e cada região tem seu próprio ritmo:', foot: 'Não se preocupe se você não sabe dançar — até o fim da noite, você vai saber.', items: [
        { name: 'Samba', desc: 'O coração do Rio e do Carnaval.', img: '/images/music-samba.jpg' },
        { name: 'Forró & baião', desc: 'Ritmos de sanfona do Nordeste, feitos para dançar a dois.', img: '/images/music-forro.png' },
        { name: 'Olodum & axé', desc: 'O pop alegre e cheio de energia da Bahia.', img: '/images/music-olodum.png' },
        { name: 'Sertanejo', desc: 'A música do interior, que você vai ouvir em todo canto.', img: '/images/music-sertanejo.png' },
        { name: 'Funk', desc: 'Ritmo urbano e dançante do Rio de Janeiro e São Paulo.', img: '/images/music-funk.png' },
      ] },
      trip: { title: 'Aproveite a viagem',
        lead: 'Brasília fica no centro do país, com conexões rápidas para o litoral e além. Se você vai voar até aqui, vale conhecer mais do Brasil.',
        items: [
          { name: 'Rio de Janeiro', desc: 'Praias, Cristo Redentor e Pão de Açúcar — o cartão-postal do Brasil.', img: '/images/rio de janeiro.png' },
          { name: 'Foz do Iguaçu', desc: 'Uma das maiores cataratas do mundo, na fronteira com a Argentina.', img: '/images/foz do iguacu.png' },
          { name: 'Salvador', desc: 'O coração afro-brasileiro da Bahia: cor, história e ritmo.', img: '/images/salvador.png' },
          { name: 'Floresta Amazônica', desc: 'Passeios de barco e lodges na floresta, geralmente por Manaus.', img: '/images/amazonia.png' },
          { name: 'Fernando de Noronha', desc: 'Um arquipélago protegido com as praias mais lindas do Brasil.', img: '/images/fernando de noronha.png' },
          { name: 'Porto de Galinhas', desc: 'Piscinas naturais quentes e praias protegidas por recifes, em Pernambuco.', img: '/images/porto de galinhas.png' },
          { name: 'Chapada dos Veadeiros', desc: 'O maior parque nacional do Cerrado — pertinho de Brasília.', img: '/images/chapada dos veadeiros.png' },
          { name: 'Lençóis Maranhenses', desc: 'Dunas brancas sem fim salpicadas de lagoas de água da chuva.', img: '/images/lencois maranhenses.png' },
          { name: 'Búzios, Cabo Frio & Arraial do Cabo', desc: 'Vilas de praia charmosas e água turquesa perto do Rio.', img: '/images/buzios.png' },
          { name: 'Paraty', desc: 'Cidade colonial entre a floresta e o mar.', img: '/images/paraty.png' },
          { name: 'São Paulo', desc: 'A maior cidade do Brasil: gastronomia, arte e vida noturna de primeira.', img: '/images/sao paulo.png' },
        ] } },
    brasilia: { eyebrow: 'A cidade onde você vai pousar', title: 'Brasília', photo: 'brasília · skyline modernista',
      whatTitle: 'Uma capital sem igual',
      intro: 'A capital do Brasil foi construída no cerrado e inaugurada em 1960 — uma cidade modernista imaginada pelo urbanista Lúcio Costa e pelo arquiteto Oscar Niemeyer, desenhada em forma de avião. Seus marcos de concreto e vidro lhe renderam o título de Patrimônio Mundial da UNESCO — não existe lugar igual.',
      seeLabel: 'O que ver e fazer',
      sights: [
        { name: 'Catedral de Brasília', desc: 'A coroa de vidro e luz de Niemeyer.', img: '' },
        { name: 'Congresso Nacional', desc: 'As torres gêmeas e as cúpulas na Esplanada.', img: '' },
        { name: 'Palácio do Planalto', desc: 'O gabinete do presidente, todo em vidro e curvas.', img: '' },
        { name: 'STF (Supremo Tribunal Federal)', desc: 'A mais alta corte do país, na Praça dos Três Poderes.', img: '' },
        { name: 'Praça dos Três Poderes', desc: 'O coração cívico onde se encontram os três poderes.', img: '' },
        { name: 'Memorial JK', desc: 'Túmulo e museu do fundador da cidade, Juscelino Kubitschek.', img: '' },
        { name: 'Palácio do Itamaraty', desc: 'O Ministério das Relações Exteriores, com jardins de água e arcos.', img: '' },
        { name: 'Pontão do Lago Sul', desc: 'Orla de bares e restaurantes à beira do lago — ótimo no pôr do sol.', img: '' },
        { name: 'Ponte JK', desc: 'A elegante ponte de três arcos sobre o Lago Paranoá.', img: '' },
        { name: 'Torre de TV', desc: 'Mirante gratuito com vista ampla da cidade.', img: '' },
        { name: 'Torre Digital', desc: 'A torre “flor” de Niemeyer, com mirante panorâmico.', img: '' },
        { name: 'Santuário Dom Bosco', desc: 'Uma capela banhada pela luz azul-profundo dos vitrais.', img: '' },
        { name: 'Parque da Cidade', desc: 'Um enorme parque urbano para caminhar, pedalar e fazer piquenique.', img: '' },
        { name: 'Praça dos Cristais', desc: 'Prismas de concreto esculturais sobre gramados verdes.', img: '' },
        { name: 'Lago Paranoá', desc: 'O lago da cidade — passeios ao pôr do sol, caiaque e stand-up paddle.', img: '' },
        { name: 'Chapada dos Veadeiros', desc: 'Cachoeiras e cânions a ~3h — um bate-volta pelo cerrado.', img: '' },
        { name: 'Pirenópolis', desc: 'Cidade colonial na serra, com cachoeiras, a ~2h da capital.', img: '' },
      ] },
    rsvp: { eyebrow: 'Confirmação · responda até setembro de 2026', title: 'Você vem?',
      intro: 'Vamos manter a celebração intimista. Conte para a gente se poderá vir — uma resposta por convite é perfeito.',
      notes: [
        ['Apenas adultos', 'Por mais que a gente ame as crianças, esta será uma noite para os adultos.'],
        ['Sem acompanhantes extras', 'O convite é para os nomes nele indicados. Se tiver dúvida sobre quem está incluído, é só perguntar.'],
        ['Responda até setembro de 2026', 'Assim conseguimos confirmar os números finais com o espaço.'],
      ],
      name: 'Nome completo', namePh: 'Seu nome', email: 'E-mail', emailPh: 'voce@email.com',
      attending: 'Você vai?', attendingPh: 'Sim, com alegria / Infelizmente não', guests: 'Convidados',
      note: 'Recado ou pedido de música', notePh: 'Opcional…', submit: 'Enviar confirmação',
      foot: 'Sabemos que vir até aqui é um compromisso de verdade, e não levamos isso por menos. Obrigado por fazer o esforço de celebrar conosco!' },
    registry: { eyebrow: 'Lista de presentes', title: 'Presentes',
      intro: 'Sua presença — especialmente para quem vem de longe — já é o único presente que esperamos. Como moramos fora, por favor não se preocupe em trazer nada físico. Mas, se quiser nos ajudar com a futura lua de mel, uma contribuição é muito bem-vinda.',
      ways: [['Pix', 'Para convidados no Brasil', 'Nossa chave PIX:', '[ em breve ]'], ['Venmo', 'Para convidados nos EUA', 'Nos encontre em:', '[ em breve ]'], ['Wise', 'Para convidados internacionais', 'Envie na sua moeda:', '[ em breve ]']],
      note: 'Os contatos acima serão adicionados antes do lançamento — e nenhum presente é esperado. De verdade.' },
    footer: { dateLine: '29 · 12 · 2026 — Brasília, Brasil' },
  },
};
