// content.js — all guest-facing text, in English (en) and Brazilian Portuguese (pt).
// This is the file to edit when updating names, dates, descriptions, gift handles, etc.
export const I18N = {
  en: {
    code: 'en',
    nav: { home: 'Home', party: 'People', event: 'Event', travel: 'Travel', brazil: 'Brazil', brasilia: 'Brasília', gifts: 'Gifts', invitation: 'Invitation', confirmar: 'RSVP' },
    // The invitation card is rendered as live text (see invitation.jsx) so it stays crisp
    // at any resolution and can be localised / personalised. Names are proper nouns (unchanged).
    invite: {
      preline: 'Together with their families',
      names: ['Anna Nieve Canning', 'Matheus Vieira Portela'],
      request: ['Request your presence', 'at the ceremony and celebration', 'of their marriage'],
      date: ['Tuesday, December 29th, 2026', 'at five o’clock'],
      venue: ['Espaço Renascença', 'Brasília, Brazil'],
      closing: 'Reception to follow',
    },
    hero: { eyebrow: 'We’re getting married · Brasília, Brazil', dateItalic: 'Tuesday, the twenty-ninth of December, two thousand twenty-six',
      chips: ['29 Dec 2026', '5 PM · Ceremony', 'Brasília, Brazil'] },
    couple: { eyebrow: 'The couple', title: 'Welcome',
      p1: 'We’re Anna and Matheus — and after years of building a life together, we’re finally throwing the party!',
      p2: 'We couldn’t be happier that you’ll be there to celebrate with us. This little site has everything you need to plan the trip and join us on the day.' },
    party: { eyebrow: 'Those who walk with us', title: 'Our People', namePh: 'Name Surname',
      intro: 'In Brazil, the couple is surrounded by padrinhos and madrinhas — literally the godparents of the wedding. They’re the closest family and friends who shaped our story and will stand beside us at the altar: the equivalent of groomsmen and bridesmaids elsewhere.',
      groups: [
        { group: 'Honour Attendants', people: [['Name Surname', 'Maid of Honour'], ['Name Surname', 'Best Man']] },
        { group: 'Bridesmaids', people: [['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid']] },
        { group: 'Groomsmen', people: [['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman']] },
      ],
      foot: 'There’s nothing you need to do — but if you spot a group in matching colours on the day, now you know who they are. (Names above are placeholders — the final list is coming soon.)' },
    event: { eyebrow: 'The celebration', title: 'The Event',
      intro: 'Everything happens in one place: Espaço Renascença, a green venue just minutes from central Brasília. The ceremony and the party are steps apart, so plan to spend the whole evening with us.',
      ceremony: { tag: 'Ceremony', time: '5 PM', desc: 'We’ll marry outdoors, in the beautiful open garden.' },
      reception: { tag: 'Reception', time: '6 PM', desc: 'Right next door for dinner, toasts, and dancing.' },
      rows: [
        ['Location', 'Espaço Renascença\nSetor de Mansões Park Way Quadra 13 Conj. 01 Lote 06\nBrasília, DF, Brazil'],
        ['Dress code', 'Formal (e.g. [long dresses and suits](https://www.theknot.com/content/formal-wedding-attire)). Open-air garden, so choose light, breathable fabrics.'],
        ['Weather', 'Late December is hot and humid, with a chance of quick showers. A light layer is a sensible bet.'],
      ],
      mapBtn: 'View on map' },
    travel: { eyebrow: 'For our guests from abroad', title: 'Travel',
      intro: 'Everything you need to plan the trip to Brasília — getting here, getting around, and the practical bits.',
      cards: [
        ['Getting to Brasília', 'Fly into Brasília — Juscelino Kubitschek International Airport (BSB).', [
          'Direct international: [TAP](https://www.flytap.com/) from Lisbon, [GOL](https://www.voegol.com.br/) from Miami & Orlando, [Copa](https://www.copaair.com/) from Panama City.',
          'From elsewhere, connect via São Paulo (GRU) or Rio de Janeiro (GIG). Allow at least a 2-hour layover to clear customs, immigration, and change terminals without stress.',
          '**Pro tip:** Brasília has direct flights across the whole country — a great chance to explore Brazil on the domestic carriers ([LATAM](https://www.latamairlines.com/), [GOL](https://www.voegol.com.br/), and [Azul](https://www.voeazul.com.br/)).',
        ]],
        ['Visa & entry', 'Always confirm with official government sources for the latest guidance.', [
          '**US, Canada, China & Australia:** e-Visa required (about US$80.90). Apply at the official portal at least 3 weeks ahead: [brazil.vfsevisa.com](https://brazil.vfsevisa.com).',
          '**UK & EU:** no visa required for tourism up to 90 days.',
          '**Passport:** Valid for 6+ months.',
          '**Vaccines:** None _required_ to enter Brazil, but a few are _recommended_ depending on where you’ll travel. Check out the [CDC travel health notice](https://wwwnc.cdc.gov/travel/destinations/traveler/none/brazil) and the [UK foreign travel advice](https://www.gov.uk/foreign-travel-advice/brazil/print) for Brazil.',
        ]],
        ['Where to stay', 'Most hotels sit close together in the central Hotel Sectors or by Lake Paranoá. Our recommendations:', [
          'Lake Paranoá: [Royal Tulip](https://www.booking.com/hotel/br/royal-tulip-brasilia-alvorada.html) · [Brasília Palace](https://www.booking.com/hotel/br/brasilia-palace.html) · [Golden Tulip](https://www.booking.com/hotel/br/golden-tulip-brasilia-alvorada.html).',
          'North Hotel Sector: [B Hotel](https://www.booking.com/hotel/br/b-brasilia.html) · [Mercure Brasília Líder](https://www.booking.com/hotel/br/apartments-brasilia-lider.html) · [Grand Mercure](https://www.booking.com/hotel/br/brasilia-eixo.html) · [Nobile Suites Monumental](https://www.booking.com/hotel/br/nobile-suites-monumental.html) · [Windsor Brasília](https://www.booking.com/hotel/br/windsor-brasilia.html).',
          '**Pro tip:** avoid walking around the hotel sector at night — take an Uber from the lobby. [Booking.com](https://www.booking.com) is handy for managing reservations.',
        ]],
        ['When to book', 'Late December is peak Brazilian summer and holiday season, so plan ahead.', [
          'Flights: book 4–6 months out for the best fares.',
          'Hotels: reserve early for touristic cities (like Rio or Florianópolis), especially around New Year.',
        ]],
        ['Getting around', 'Brasília was designed for cars, so distances between sights are large.', [
          'We recommend Uber: reliable, inexpensive, and the safest way to move. Official taxis are also a good option (except in Rio de Janeiro, where taxi drivers frequently overcharge tourists).',
          'Renting a car is possible with an International Driving Permit; parking is plentiful and free in most places.',
          '**Public transit is not recommended:** buses and metro have limited service, are inconvenient for tourists, and are less safe than Uber.',
        ]],
        ['Money & currency', 'The currency is the Brazilian Real (R$ / BRL). Roughly R$5 ≈ US$1, or R$6 ≈ €1 (rates vary).', [
          'Cards and contactless are universally accepted — you’ll rarely need cash. Visa and Mastercard work everywhere; Amex and Discover often don’t.',
          'If a card machine offers to convert the price, always choose to pay in Brazilian Real and let your bank do the conversion.',
          'There’s no tipping culture, except at restaurants, where a 10% service charge is already included in the bill.',
        ]],
      ] },
    brazil: { eyebrow: 'Your first time in Brazil', title: 'Brazil', photo: 'brazil · from coast to cerrado',
      intro: 'Brazil is a _massive_ country with deep history and rich culture. Here’s our first-timer’s guide to making the most of your visit.',
      watch: { title: 'Watch before you come',
        lead: 'A few short videos are a lovely way to arrive already in the mood. If it’s your first time in Brazil, these set the scene:',
        videos: [
          ['Dots on a Map — Brasília', 'https://www.youtube.com/watch?v=HbS_nmFAddk'],
          ['Dots on a Map — Rio de Janeiro', 'https://www.youtube.com/watch?v=3FioV9MwBOA'],
          ['Dots on a Map — Salvador', 'https://www.youtube.com/watch?v=53qpaG8Q2OA'],
          ['Dots on a Map — Florianópolis', 'https://www.youtube.com/watch?v=iS022g0kT9A'],
          ['Dots on a Map — São Paulo', 'https://www.youtube.com/watch?v=tvaXa7HS7ow'],
          ['Best Places to Visit in Brazil', 'https://www.youtube.com/watch?v=q7zdJ-nMrlE'],
          ['What Tourists Should Know about Brazil', 'https://www.youtube.com/watch?v=NXtnHGvhIQg'],
          ['Brazil in 2 Weeks', 'https://www.youtube.com/watch?v=sremk7jo15k'],
          ['Phrases you need before you travel to Brazil', 'https://www.youtube.com/watch?v=eMsDho6otek'],
        ] },
      info: [
        { icon: 'wifi', title: 'Staying connected (eSIM)', lead: 'Getting online in Brazil is easy and cheap:', items: [
          ['The simplest option', 'is a travel eSIM you buy before you fly. [Airalo](https://www.airalo.com) (referral code MATHEU7267 for $3 off), Holafly, or Saily activate the moment you land — no swapping your physical SIM or paying inflated roaming.'],
          ['A local SIM', 'from Vivo, Claro, or TIM is cheaper still, but usually needs a Brazilian CPF (tax ID), which most visitors don’t have.'],
          ['Coverage', 'is excellent in every major city, and Wi-Fi is widespread in hotels, restaurants, and malls — just ask the staff for the password.'],
          ['Pro tip:', 'mobile data is essential here — you’ll need it for Uber, maps, and translation.'],
        ] },
        { icon: 'chat', title: 'Language', lead: 'The language is Portuguese — its own language, distinct from Spanish (though Spanish helps you catch the gist).', items: [
          ['English', 'is not widely spoken outside hotels and tourist spots, so don’t rely on it for everyday situations.'],
          ['Google Translate', 'goes a long way — its camera and conversation modes are lifesavers. Download the offline Portuguese pack just in case.'],
          ['Don’t be shy:', 'Brazilians are famously warm and will go out of their way to help. A smiling “obrigado / obrigada” (thank you) opens every door.'],
        ] },
        { icon: 'money', title: 'Cost of living', lead: 'For most international visitors, Brazil is great value:', items: [
          ['Flights', 'are the big-ticket item — international fares have climbed with oil prices, so book as early as you can.'],
          ['Everything else', '— food, transport, and entertainment — is noticeably cheaper than in the US or Europe. A great meal or a long Uber ride won’t break the bank.'],
          ['Day to day', 'is simple: cards are accepted everywhere and the exchange rate is favourable (roughly R$5 ≈ US$1).'],
        ] },
        { icon: 'sun', title: 'Weather', lead: 'Pack for heat. Late December is high summer in Brazil — if you’re escaping a northern winter, the contrast will be dramatic.', items: [
          ['Brasília & the south/southeast:', 'warm, humid, and in the rainy season — bright days broken by short, heavy afternoon showers. It’s common to just wait the rain out.'],
          ['The northeast:', 'hot and noticeably drier — perfect beach weather.'],
          ['The north (Amazon):', 'hot and humid year-round, with little seasonal change.'],
          ['Everywhere:', 'sunscreen, a hat, light clothes, and a refillable water bottle are your friends.'],
        ] },
        { icon: 'health', title: 'Health & vaccines', lead: 'A few practical health notes for your trip:', items: [
          ['Vaccines', 'No vaccines are _required_ to enter Brazil, but a few are _recommended_ depending on where you’ll travel. Check the [CDC travel health notice](https://wwwnc.cdc.gov/travel/destinations/traveler/none/brazil) and the [UK foreign travel advice](https://www.gov.uk/foreign-travel-advice/brazil/print) for the latest guidance.'],
          ['Tap water', 'Don’t drink the tap water anywhere in Brazil — stick to bottled or filtered water. Most homes, hotels, and restaurants have a filter you can refill from.'],
        ] },
        { icon: 'shield', title: 'Staying safe', lead: 'Brazil is wonderfully welcoming, but a little street sense goes a long way if you’re coming from a much safer country:', items: [
          ['Keep valuables low-key.', 'Don’t flash jewellery, watches, or your phone on the street — use your phone inside shops or restaurants.'],
          ['Mind where you go.', 'Stick to busy, well-lit, touristy areas and avoid empty streets. Ask your hotel which neighbourhoods to skip, and **never** visit favelas.'],
          ['Split your essentials.', 'Carry a copy of your passport’s photo page and leave the original at the hotel; bring two cards and leave one behind.'],
          ['Watch your belongings.', 'Don’t leave bags, phones, or cameras unattended — on the beach, at a table, or anywhere else.'],
          ['Crossing the street.', 'Brasília is the rare Brazilian city where cars yield to pedestrians; almost everywhere else they often _don’t_ — even at crosswalks. Cross with care and prefer crossings with traffic lights.'],
          ['Travel advisory.', 'For the latest official guidance, see the [UK travel advice](https://www.gov.uk/foreign-travel-advice/brazil/print) and the [U.S. State Department advisory](https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/brazil-travel-advisory.html) for Brasil.'],
        ], foot: 'None of this should make you anxious — reach out to us if you have any questions or concerns!' },
      ],
      biomes: { title: 'Brazil’s biomes', lead: 'Brazil is continental in scale, and the landscape changes completely from one region to the next. There are six great biomes:', items: [
        { name: 'Amazônia', desc: 'The world’s largest rainforest: dense, wet, and teeming with life.', img: '/images/biome-amazonia.webp' },
        { name: 'Mata Atlântica', desc: 'The lush Atlantic Forest along the coast, hugging cities like Rio and São Paulo.', img: '/images/biome-mata-atlantica.webp' },
        { name: 'Cerrado', desc: 'The tropical savanna around Brasília: twisted trees, vast skies, surprising biodiversity.', img: '/images/biome-cerrado.webp' },
        { name: 'Pantanal', desc: 'The planet’s largest tropical wetland, and the best place in Brazil to spot wildlife.', img: '/images/biome-pantanal.webp' },
        { name: 'Caatinga', desc: 'The semi-arid scrubland of the northeast, found nowhere else on earth.', img: '/images/biome-caatinga.webp' },
        { name: 'Pampas', desc: 'The rolling grasslands of the far south, gaúcho country.', img: '/images/biome-pampas.webp' },
      ] },
      food: { title: 'Food', lead: 'Come hungry. Brazilian cooking is generous, regional, and made for sharing:', foot: 'Brazil has a surprisingly large repertoire of gluten-free options.', items: [
        { name: 'Churrasco', desc: 'Brazilian barbecue, endless cuts of grilled meat.', img: '/images/food-churrasco.webp' },
        { name: 'Feijoada', desc: 'The national dish: a rich black-bean and pork stew, best over a long, lazy lunch with cold beer and live music.', img: '/images/food-feijoada.webp' },
        { name: 'Farofa', desc: 'Toasted cassava flour, the crunchy companion to almost everything.', img: '/images/food-farofa.webp' },
        { name: 'Moqueca', desc: 'A fragrant fish stew with coconut milk, tomato, and palm oil.', img: '/images/food-moqueca.webp' },
        { name: 'Acarajé', desc: 'Bahian street food of Nigerian origin, packed with flavour.', img: '/images/food-acaraje.webp' },
        { name: 'Pão de queijo', desc: 'Warm, chewy cheese bread; impossible to eat just one.', img: '/images/food-pao-de-queijo.webp' },
        { name: 'Coxinha', desc: 'Teardrop-shaped fried chicken croquettes, the king of snacks.', img: '/images/food-coxinha.webp' },
        { name: 'Açaí', desc: 'Frozen Amazonian berry bowls, served thick and cold.', img: '/images/food-acai.webp' },
        { name: 'Tapioca', desc: 'Cassava crêpes, sweet or savoury.', img: '/images/food-tapioca.webp' },
        { name: 'Brigadeiro', desc: 'Chocolate fudge balls, the classic sweet.', img: '/images/food-brigadeiro.webp' },
        { name: 'Pudim', desc: 'Brazilian-style caramel flan.', img: '/images/food-pudim.webp' },
        { name: 'Caipirinha', desc: 'The national cocktail: cachaça, lime, sugar, and ice.', img: '/images/food-caipirinha.webp' },
      ] },
      holidays: { title: 'Christmas & New Year’s Eve', lead: 'Our wedding falls right between Brazil’s two biggest holidays, so it helps to know how the country celebrates:', items: [
        { name: 'Christmas (24–25 Dec)', desc: 'A warm, family affair — the main celebration is dinner on the night of the 24th, and most shops and restaurants close on the 24th and 25th.', img: '/images/holiday-christmas.webp' },
        { name: 'New Year’s Eve (Réveillon)', desc: 'A national party, best by the sea: wear all white and jump seven waves at midnight. The biggest celebrations are in Rio, Florianópolis, Salvador, and Recife. Hotels sell out early, so book ahead.', img: '/images/holiday-new-years-eve.webp' },
      ] },
      music: { title: 'Music & dance', lead: 'Music is everywhere in Brazil, and every region has its own beat:', foot: 'Don’t worry if you can’t dance — by the end of the night, you will.', items: [
        { name: 'Samba', desc: 'The heartbeat of Rio, and of Carnival. Look out for [samba groups at the beaches](https://www.youtube.com/watch?v=wGaWVuBIyGY) and [samba de gafieira](https://youtu.be/S7ExdpVmVBw?si=exTOyiG768jRxEWf&t=65) in parties. Other important subgenres include the [pagode](https://www.youtube.com/watch?v=c4XeTP11EI8) and the [samba-enredo](https://www.youtube.com/watch?v=PEcYx_Tljbo) (the one from the world famous Rio de Janeiro Carnaval parade).', img: '/images/music-samba.webp' },
        { name: 'Forró', desc: 'Rhythm from the Northeast Brazil, with instruments such as the accordion, triangle, and percursion. [Forró](https://www.youtube.com/watch?v=RacuiR1vpKg) is the most popular partner dance genre in the entire country. Check out other sub-genres such as the [xote](https://www.youtube.com/watch?v=QDAHMMMtFBI), the [baião](https://www.youtube.com/watch?v=ZeZ0B36sy1c), and the [xaxado](https://www.youtube.com/watch?v=G8GADCfpavU).', img: '/images/music-forro.webp' },
        { name: 'Olodum & axé', desc: 'High-energy, percussive rhythms from Bahia. [Olodum](https://www.youtube.com/watch?v=A3o30YJiWsc), played by a drum orchestra and heavily inspired by African music, is commonly found in the streets of Salvador. [Axé](https://www.youtube.com/watch?v=xNo2kP7HJyw) is the rhythm of the Carnaval in Bahia. Also check out [maracatu](https://www.youtube.com/watch?v=DqZX8m2T-e0), another percursive genre from Pernambuco.', img: '/images/music-olodum.webp' },
        { name: 'Sertanejo', desc: 'Brazil’s country music and the most listened genred in Brazil, it has strong influences from American Country and Mexican Mariachi music. Check out some of the sub-genres, such as the traditional [moda de viola](https://www.youtube.com/watch?v=JSFj3UGaO3Y), the millenial [sertanejo universitário](https://www.youtube.com/watch?v=rS2FDyOKR2g), and the modern [agronejo](https://www.youtube.com/watch?v=vBPuW9IerfU).', img: '/images/music-sertanejo.webp' },
        { name: 'Funk', desc: 'Urban music to dance in Rio de Janeiro and São Paulo, it received a lot of influence from Hip Hop, Miami Bass, and Freestyle. Subgenres include [funk carioca](https://www.youtube.com/watch?v=am3U2a_wpV4), [funk ostentação](https://www.youtube.com/watch?v=V1sRhopUw44), [funk melody](https://www.youtube.com/watch?v=PVV5qQl_HDo), [ravefunk](https://www.youtube.com/watch?v=SmpNmsuNA2E), [trapfunk](https://www.youtube.com/watch?v=aHBW_Nd_z8k), and [eletrofunk](https://www.youtube.com/watch?v=7CF5qbw8zec).', img: '/images/music-funk.webp' },
        { name: 'Choro', desc: 'Brazil’s first-ever music genre: [fast, virtuosic, and instrumental](https://www.youtube.com/watch?v=fgrGb5cx2SA), born in 19th-century Rio by mixing [European chamber music](https://www.youtube.com/watch?v=kdLKTDsm3EA), [African percursion](https://www.youtube.com/watch?v=wA9tUYS4sc4), and [Native Brazilian rhythms](https://www.youtube.com/watch?v=9RUO1E5AS0M). Typically played by [musicians in a round table](https://www.youtube.com/watch?v=WLT6AkL8U7U), Choro is [usually instrumental](https://www.youtube.com/watch?v=PusYdptMjXM) and features [tons of improvisation](https://www.youtube.com/watch?v=pn2FlgUfMM4) by virtuoso players [akin to Jazz](https://www.youtube.com/watch?v=RWXqlJ0Zydc). Make sure to head out to [Brasília’s Clube do Choro](https://www.youtube.com/watch?v=rHcRes2wUpo) and watch some of the best musicians in the country live!', img: '/images/music-choro.webp' },
      ] },
      trip: { title: 'Make it a trip',
        lead: 'Brasília sits at the centre of the country, with quick connections to the coast and beyond. If you’re flying this far, it’s worth seeing more of Brazil.',
        items: [
          { name: 'Rio de Janeiro', desc: 'Beaches, Christ the Redeemer, and Sugarloaf — Brazil’s postcard city.', img: '/images/rio de janeiro.webp' },
          { name: 'São Paulo', desc: 'Brazil’s biggest city: world-class food, art, and nightlife.', img: '/images/sao paulo.webp' },
          { name: 'Belo Horizonte', desc: 'The capital of Minas Gerais — legendary boteco bars and the gateway to its colonial towns.', img: '/images/travel-belo-horizonte.webp' },
          { name: 'Salvador', desc: 'The Afro-Brazilian heart of Bahia: colour, history, and rhythm.', img: '/images/salvador.webp' },
          { name: 'Recife', desc: 'A historic northeastern capital, paired with colourful Olinda next door.', img: '/images/travel-recife.webp' },
          { name: 'Florianópolis', desc: 'An island city of 40+ beaches and lagoons — and a New Year’s favourite.', img: '/images/travel-florianopolis.webp' },
          { name: 'Manaus & Amazon Rainforest', desc: 'River journeys and rainforest lodges in the largest tropical forest in the world.', img: '/images/amazonia.webp' },
          { name: 'Foz do Iguaçu', desc: 'One of the world’s great waterfalls, on the Argentine border.', img: '/images/foz do iguacu.webp' },
          { name: 'Lençóis Maranhenses', desc: 'Endless white dunes dotted with rain-fed lagoons.', img: '/images/lencois maranhenses.webp' },
          { name: 'Fernando de Noronha', desc: 'A protected archipelago with Brazil’s most beautiful beaches.', img: '/images/fernando de noronha.webp' },
          { name: 'Chapada dos Veadeiros', desc: 'The largest national park in the Cerrado biome — pretty close to Brasília.', img: '/images/chapada dos veadeiros.webp' },
          { name: 'Porto de Galinhas', desc: 'Warm natural pools and reef-sheltered beaches in Pernambuco.', img: '/images/porto de galinhas.webp' },
          { name: 'Búzios, Cabo Frio & Arraial do Cabo', desc: 'Chic beach towns and turquoise water near Rio.', img: '/images/buzios.webp' },
          { name: 'Ouro Preto', desc: 'A baroque colonial gem in the mountains of Minas — a UNESCO World Heritage site.', img: '/images/travel-ouro-preto.webp' },
          { name: 'Paraty', desc: 'A colonial port town between rainforest and sea.', img: '/images/paraty.webp' },
          { name: 'Pirenópolis', desc: 'A colonial mountain town with waterfalls, a couple of hours from Brasília.', img: '/images/travel-pirenopolis.webp' },
          { name: 'Jericoacoara', desc: 'A remote dune-and-beach village in Ceará, famed for its sunsets.', img: '/images/travel-jericoacoara.webp' },
        ] } },
    brasilia: { eyebrow: 'The city you’re flying into', title: 'Brasília', photo: 'brasília · modernist skyline',
      whatTitle: 'A modernist artwork',
      intro: '[Brazil’s capital](https://en.wikipedia.org/wiki/Brasília) was built from open savanna and inaugurated in 1960 — a modernist city imagined by urban planner [Lúcio Costa](https://en.wikipedia.org/wiki/Lúcio_Costa) and architect [Oscar Niemeyer](https://en.wikipedia.org/wiki/Oscar_Niemeyer), laid out in the shape of an aeroplane. Its sweeping concrete-and-glass landmarks earned it UNESCO World Heritage status, and it’s unlike anywhere else on earth.',
      seeLabel: 'Things to see & do',
      sights: [
        { name: 'Cathedral of Brasília', desc: 'Niemeyer’s crown of glass and light, [this stunning cathedral](https://en.wikipedia.org/wiki/Cathedral_of_Brasília) is round and displays floating angels, made out of concrete, against beautifully crafted stained glass. A must see!', img: '/images/brasilia-catedral.webp' },
        { name: 'National Congress', desc: 'The twin towers and domes on the Esplanade of Ministries, it houses [Brazil’s Chamber of Deputies and Senate](https://en.wikipedia.org/wiki/National_Congress_Palace). Those familiar with the [United Nations Headquarters](https://en.wikipedia.org/wiki/Headquarters_of_the_United_Nations) in New York City will notice some similarities, after all, the UN building was designed by the very same Oscar Niemeyer and his mentor, Le Corbusier', img: '/images/brasilia-congresso.webp' },
        { name: 'Palácio do Planalto', desc: 'The [president’s office](https://en.wikipedia.org/wiki/Palácio_do_Planalto), all glass and curves. The building seems to be floating due to its curved pillars gently touching the ground.', img: '/images/brasilia-palacio-do-planalto.webp' },
        { name: 'Supreme Federal Court', desc: 'Brazil’s [highest court](https://en.wikipedia.org/wiki/Supreme_Federal_Court), on the [Praça dos Três Poderes](https://en.wikipedia.org/wiki/Praça_dos_Três_Poderes): a single plaza housing the seats of all three branches of the government.', img: '/images/brasilia-stf.webp' },
        { name: 'Itamaraty Palace', desc: 'The [foreign ministry](https://en.wikipedia.org/wiki/Itamaraty_Palace), with water gardens and arches. Designed by Oscar Niemeyer and landscaped by [Burle Marx](https://en.wikipedia.org/wiki/Roberto_Burle_Marx), it is probably the apex of Brazilian modernism. Make sure to visit its iconic spiral staircase and rooftop garden. [Schedule a visit ahead of time here](https://www.gov.br/mre/pt-br/assuntos/palacio-itamaraty/visite-o-itamaraty).', img: '/images/brasilia-itamaraty.webp' },
        { name: 'Palácio da Justiça', desc: 'The [Ministry of Justice](https://pt.wikipedia.org/wiki/Palácio_da_Justiça_%28Brasília%29), across the street from the Itamaraty Palace, it displays impressive brutalist-style waterfalls and tropical plants. The perfect merger of the artificial and the natural.', img: '/images/brasilia-palacio-da-justica.webp' },
        { name: 'Museu da República', desc: 'A [futurist museum](https://museu.cultura.df.gov.br/#) with rotating modern-art exhibitions.', img: '/images/brasilia-museu-da-republica.webp' },
        { name: 'Teatro Nacional', desc: 'A modernist theatre, home to the Brasília Symphony Orchestra.', img: '/images/brasilia-teatro-nacional.webp' },
        { name: 'Ponte JK', desc: 'The graceful triple-arch bridge over Lake Paranoá. Drive your car through the bridge or have dinner at one of the many restaurants by the lake.', img: '/images/brasilia-ponte-jk.webp' },
        { name: 'TV Tower', desc: 'A [free observation deck](https://www.turismo.df.gov.br/torre-de-tv/) with sweeping city views. Enjoy a beautiful sunset while eating at the cafe inside.', img: '/images/brasilia-torre-de-tv.webp' },
        { name: 'Digital TV Tower', desc: 'Niemeyer’s “flower” tower with [a panoramic lookout](https://www.df.gov.br/torre-de-tv-digital/) at the top of a hill, where you may enjoy a beautiful view of the entire Federal District.', img: '/images/brasilia-torre-digital.webp' },
        { name: 'University of Brasília', desc: 'The campus of one of the country’s top universities, blending brutalism and nature. Check out the [Central Science Institute](https://maps.app.goo.gl/rkCkYQx7wBSSbZK16) — a single building spanning over 1 km —, the [President’s Office](https://maps.app.goo.gl/P3zY4sVgM367zozX8) — blending brutalism and nature —, and the [Central Library](https://maps.app.goo.gl/nyGXCDhmuLux7eQD8).', img: '/images/brasilia-unb.webp' },
        { name: 'Santuário Dom Bosco', desc: 'A [chapel](https://maps.app.goo.gl/LEvtQtT7rkzFs4aH8) distinguished by its blue floor-to-ceiling windows on all sides & a huge Murano chandelier. Visit during a sunny day for maximum effect.', img: '/images/brasilia-santuario-dom-bosco.webp' },
        { name: 'Pontão do Lago Sul', desc: '[Lively hangout](https://maps.app.goo.gl/sE4ezYVh1ZBDwMrm8) along Lake Paranoá featuring palm-lined walking paths, cafes & views of JK Bridge. Great spot for an afternoon stroll or dinner.', img: '/images/brasilia-pontao.webp' },
        { name: 'Igrejinha', desc: 'A small, modern [Catholic chapel](https://maps.app.goo.gl/ZRRZgki4CQETXazw8) with [Athos Bulcão](https://en.wikipedia.org/wiki/Athos_Bulcão) tilework, a Brasília signature.', img: '/images/brasilia-igrejinha.webp' },
        { name: 'Parque da Cidade', desc: 'A [vast urban park](https://maps.app.goo.gl/RhupSgqhwkunHuVZ9) for walking, cycling, exercising, and picnics. Great place for late afternoon jogging followed by fresh coconut water and açaí. Make sure to wear sunscreen and bring your sunglasses: the sun is intense here!', img: '/images/brasilia-parque-da-cidade.webp' },
        { name: 'Praça dos Cristais', desc: '[32-acre triangular plaza](https://maps.app.goo.gl/VUWktsmKB3qNAWYB6) by architect [Burle Marx](https://en.wikipedia.org/wiki/Roberto_Burle_Marx), featuring sculptures, reflecting pools & pathways. It faces the headquarters of the Brazilian Armed Forces.', img: '/images/brasilia-praca-dos-cristais.webp' },
        { name: 'Parque Olhos d\'Água', desc: 'A small neighbourhood park with plently of nature, shaded trails for walking & jogging, and a lake with local fauna. A local favorite!', img: '/images/brasilia-parque-olhos-dagua.webp' },
        { name: 'Lago Paranoá', desc: 'The city’s lake — sunset cruises, kayaking, and stand-up paddle.', img: '/images/brasilia-lago-paranoa.webp' },
        { name: 'Água Mineral', desc: '[A forest reserve inside the city](https://maps.app.goo.gl/tkkPoLZDbp3N2kDg8), with trails and a public pool. Experience the Cerrado without leaving the city.', img: '/images/brasilia-agua-mineral.webp' },
        { name: 'Ermida Dom Bosco', desc: '[A natural lookout](https://maps.app.goo.gl/dDHUF9K82CLYVbk68) with a spectacular sunset. A hidden gem.', img: '/images/brasilia-ermida-dom-bosco.webp' },
        { name: 'Eixão do lazer', desc: 'Sport, culture, and food at the city’s [main expressway](https://maps.app.goo.gl/xpMQ9ubn2Ljg5a7p8), closed to cars on Sundays and holidays.', img: '/images/brasilia-eixao-do-lazer.webp' },
        { name: 'Salto do Itiquira', desc: 'A forest reserve [near Brasília](https://maps.app.goo.gl/TscCAXqMmpka4EpK8) with one of the country’s tallest waterfalls.', img: '/images/brasilia-salto-do-itiquira.webp' },
        { name: 'Chapada dos Veadeiros', desc: '[Waterfalls and canyons](https://maps.app.goo.gl/59vTM4SqYKoGPCfCA) ~3h away from Brasília — a cerrado day trip.', img: '/images/chapada dos veadeiros.webp' },
        { name: 'Pirenópolis', desc: 'A [colonial mountain town](https://maps.app.goo.gl/RMaiLHaJb7khMB5j8) with waterfalls, ~2h from the city.', img: '/images/brasilia-pirenopolis.webp' },
      ],
      eatLabel: 'Where to eat & drink',
      eatLead: 'Brasília has hundreds of quaint coffee shops, cafés, bars, and restaurants. These are some of our favorites!',
      eat: [
        { name: 'Ernesto Café', desc: '[Sophisticated, intimate café](https://maps.app.goo.gl/LpNoy9LYwLgr8CMh8) for book lovers, serving hot drinks & appetizers.', img: '/images/brasilia-coffee-shops.webp' },
        { name: 'Mangai', desc: 'A generous Northeastern Brazilian buffet — hearty regional comfort food.', img: '' },
        { name: 'Coco Bambu', desc: 'Big-portion seafood, a Brazilian crowd-pleaser.', img: '' },
        { name: 'Beirute', desc: 'A Brasília institution in Asa Sul: a lively bar-restaurant for cold beer and petiscos.', img: '' },
        { name: 'Bar Brasília', desc: 'A classic boteco with draft beer and traditional Brazilian bar food.', img: '' },
        { name: 'Clube do Choro', desc: 'Live Brazilian choro music with drinks and a bite.', img: '' },
      ] },
    rsvp: { eyebrow: 'RSVP · please reply by September 2026', title: 'Will you come?',
      intro: 'We’re keeping the celebration intimate. Let us know if you can make it.',
      notes: [
        ['Adults only', 'As much as we love the little ones, this will be a grown-ups’ evening.'],
        ['No plus-ones', 'Your invitation is for the names printed on it. If you’re unsure whether a guest is included, just ask us.'],
        ['Reply by September 2026', 'So we can confirm final numbers with the venue.'],
      ],
      name: 'Full name', namePh: 'Your name', email: 'Email', emailPh: 'you@email.com',
      attending: 'Attending?', attendingPh: 'Choose…', yes: 'Joyfully yes', no: 'Sadly, no',
      guests: 'Guests', note: 'A note or song request', notePh: 'Optional…',
      submit: 'Send RSVP', sending: 'Sending…', soon: 'Soon',
      thanks: 'Thank you — your response is in!', thanksBody: 'We can’t wait to celebrate with you.',
      error: 'Something went wrong. Please try again, or email us at matheus@matheusportela.com.',
      foot: 'We know travelling here is a real commitment, and we don’t take it for granted. Thank you for making the effort to celebrate with us!' },
    registry: { eyebrow: 'Gift list', title: 'Gifts',
      intro: 'Your presence — especially for those flying a long way — is genuinely the only gift we’re hoping for. Since we live abroad, please don’t worry about bringing anything physical. If you’d still like to help with our future honeymoon, a contribution is warmly welcomed.',
      ways: [['Pix', 'Brazil transfers\n(Reais)', 'Email:', 'btg@matheusportela.com'], ['Venmo', 'US transfers\n(Dollars)', 'Handle:\n(last 4 digits of phone number: 7457)', '@matheusportela'], ['Zelle', 'US transfers\n(Dollars)', 'Email:', 'matheus@matheusportela.com'], ['EU', 'European transfers\n(Euros)', 'IBAN:', '**Name:** MATHEUS VIEIRA PORTELA\n**IBAN:** BE22 9672 4991 8947\n**SWIFT/BIC:** TRWIBEB1XXX\n**Bank name and address:**\nWise, Rue du Trône 110, 3rd floor, Brussels, 1050, Belgium'], ['Wise', 'International transfers\n(all currencies)', 'Handle:', '@matheusv65'], ['Others', '', 'If you want to gift us but cannot use any of the previous methods, let us know!']],
      note: 'No gift is ever expected. Truly!' },
    footer: { dateLine: '29 · 12 · 2026 — Brasília, Brazil' },
  },

  pt: {
    code: 'pt',
    nav: { home: 'Início', party: 'Padrinhos', event: 'Evento', travel: 'Viagem', brazil: 'Brasil', brasilia: 'Brasília', gifts: 'Presentes', invitation: 'Convite', confirmar: 'Confirmar' },
    invite: {
      preline: 'Junto com suas famílias',
      names: ['Anna Nieve Canning', 'Matheus Vieira Portela'],
      request: ['Solicitam sua presença', 'na cerimônia e celebração', 'de seu casamento'],
      date: ['Terça-feira, 29 de dezembro de 2026', 'às dezessete horas'],
      venue: ['Espaço Renascença', 'Brasília, Brasil'],
      closing: 'Recepção a seguir',
    },
    hero: { eyebrow: 'Nós vamos casar · Brasília, Brasil', dateItalic: 'terça-feira, vinte e nove de dezembro de dois mil e vinte e seis',
      chips: ['29 Dez 2026', '17h · Cerimônia', 'Brasília, Brasil'] },
    couple: { eyebrow: 'O casal', title: 'Bem-vindos',
      p1: 'Somos Anna e Matheus — e depois de anos construindo uma vida juntos, vamos finalmente fazer a festa!',
      p2: 'Não poderíamos estar mais felizes em ter você conosco para celebrar. Este site reúne tudo o que você precisa para planejar a viagem e participar do nosso grande dia.' },
    party: { eyebrow: 'Quem caminha conosco', title: 'Padrinhos', namePh: 'Nome Sobrenome',
      intro: 'No Brasil, os noivos são cercados por padrinhos e madrinhas — as pessoas mais próximas, que fizeram parte da nossa história e estarão ao nosso lado no altar.',
      groups: [
        { group: 'Padrinhos de Honra', people: [['Nome Sobrenome', 'Madrinha de Honra'], ['Nome Sobrenome', 'Padrinho de Honra']] },
        { group: 'Madrinhas', people: [['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha']] },
        { group: 'Padrinhos', people: [['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho']] },
      ],
      foot: 'Você não precisa fazer nada — mas, se vir um grupo com as mesmas cores no dia, agora você sabe quem são. (Os nomes acima são exemplos — a lista final vem em breve.)' },
    event: { eyebrow: 'A celebração', title: 'Evento',
      intro: 'Tudo acontece em um só lugar: o Espaço Renascença, um espaço verde a poucos minutos do centro de Brasília. A cerimônia e a festa são lado a lado, então reserve a noite toda para celebrar conosco.',
      ceremony: { tag: 'Cerimônia', time: '17h', desc: 'Vamos nos casar ao ar livre, no lindo jardim aberto.' },
      reception: { tag: 'Recepção', time: '18h', desc: 'Logo ao lado, com jantar, brindes e muita dança.' },
      rows: [
        ['Local', 'Espaço Renascença\nSetor de Mansões Park Way Quadra 13 Conj. 01 Lote 06\nBrasília, DF, Brasil'],
        ['Traje', 'Formal (como [vestidos longos e ternos](https://www.theknot.com/content/formal-wedding-attire)). Jardim ao ar livre, então prefira tecidos leves e frescos.'],
        ['Clima', 'O fim de dezembro é quente e úmido, com chance de chuva rápida. Leve um casaco leve por garantia.'],
      ],
      mapBtn: 'Ver no mapa' },
    travel: { eyebrow: 'Para nossos convidados de fora', title: 'Viagem',
      intro: 'Tudo o que você precisa para planejar a viagem a Brasília — como chegar, como se locomover e os detalhes práticos.',
      cards: [
        ['Como chegar a Brasília', 'Voe até o Aeroporto Internacional de Brasília — Juscelino Kubitschek (BSB).', [
          'Voos diretos internacionais: [TAP](https://www.flytap.com/) de Lisboa, [GOL](https://www.voegol.com.br/) de Miami e Orlando, [Copa](https://www.copaair.com/) do Panamá.',
          'De outros lugares, conecte por São Paulo (GRU) ou Rio de Janeiro (GIG). Reserve ao menos 2h de conexão para passar pela imigração e trocar de terminal com tranquilidade.',
          '**Dica:** Brasília tem voos diretos para todo o país — uma ótima chance de explorar o Brasil pelas companhias domésticas ([LATAM](https://www.latamairlines.com/), [GOL](https://www.voegol.com.br/) e [Azul](https://www.voeazul.com.br/)).',
        ]],
        ['Visto & entrada', 'Sempre confirme nas fontes oficiais do governo para a orientação mais recente.', [
          '**EUA, Canadá, China e Austrália:** e-Visa obrigatório (cerca de US$80,90). Solicite no portal oficial com pelo menos 3 semanas de antecedência: [brazil.vfsevisa.com](https://brazil.vfsevisa.com).',
          '**Reino Unido e UE:** sem visto para turismo até 90 dias.',
          '**Passaporte:** válido por 6+ meses.',
          '**Vacinas:** nenhuma é _exigida_ para entrar no Brasil, mas algumas são _recomendadas_ dependendo de para onde você vai. Veja o [aviso de saúde do CDC](https://wwwnc.cdc.gov/travel/destinations/traveler/none/brazil) e o [aviso para viajantes do Reino Unido](https://www.gov.uk/foreign-travel-advice/brazil/print).',
        ]],
        ['Onde ficar', 'A maioria dos hotéis fica próxima nos Setores Hoteleiros centrais ou à beira do Lago Paranoá. Nossas recomendações:', [
          'Lago Paranoá: [Royal Tulip](https://www.booking.com/hotel/br/royal-tulip-brasilia-alvorada.html) · [Brasília Palace](https://www.booking.com/hotel/br/brasilia-palace.html) · [Golden Tulip](https://www.booking.com/hotel/br/golden-tulip-brasilia-alvorada.html).',
          'Setor Hoteleiro Norte: [B Hotel](https://www.booking.com/hotel/br/b-brasilia.html) · [Mercure Brasília Líder](https://www.booking.com/hotel/br/apartments-brasilia-lider.html) · [Grand Mercure](https://www.booking.com/hotel/br/brasilia-eixo.html) · [Nobile Suites Monumental](https://www.booking.com/hotel/br/nobile-suites-monumental.html) · [Windsor Brasília](https://www.booking.com/hotel/br/windsor-brasilia.html).',
          '**Dica:** evite andar a pé pelo setor hoteleiro à noite — pegue um Uber na portaria. O [Booking.com](https://www.booking.com) facilita gerenciar as reservas.',
        ]],
        ['Quando reservar', 'O fim de dezembro é alta temporada de verão e festas, então planeje com antecedência.', [
          'Voos: reserve com 4–6 meses para os melhores preços.',
          'Hotéis: reserve cedo para cidades turísticas (como Rio ou Florianópolis), especialmente perto do Ano Novo.',
        ]],
        ['Como se locomover', 'Brasília foi feita para carros, então as distâncias entre os pontos são grandes.', [
          'Recomendamos o Uber: confiável, barato e o jeito mais seguro de circular. Táxis oficiais também são uma boa opção (exceto no Rio de Janeiro, onde os taxistas frequentemente cobram a mais dos turistas).',
          'Alugar carro é possível com Permissão Internacional para Dirigir; estacionamento é abundante e gratuito na maioria dos lugares.',
          '**O transporte público não é recomendado:** ônibus e metrô têm cobertura limitada, são pouco práticos para turistas e menos seguros que o Uber.',
        ]],
        ['Dinheiro & moeda', 'A moeda é o Real (R$ / BRL). Aproximadamente R$5 ≈ US$1, ou R$6 ≈ €1 (varia).', [
          'Cartões e aproximação são aceitos em todo lugar — dificilmente você vai precisar de dinheiro. Visa e Mastercard funcionam em qualquer lugar; Amex e Discover, muitas vezes não.',
          'Se a maquininha oferecer conversão de moeda, escolha sempre pagar em Real e deixe seu banco fazer a conversão.',
          'Não há cultura de gorjeta, exceto em restaurantes, onde os 10% de serviço já vêm na conta.',
        ]],
      ] },
    brazil: { eyebrow: 'Sua primeira vez no Brasil', title: 'Brasil', photo: 'brasil · do litoral ao cerrado',
      intro: 'O Brasil é um país _imenso_, de história profunda e cultura rica. Este é o nosso guia para quem visita o país pela primeira vez.',
      watch: { title: 'Assista antes de vir',
        lead: 'Alguns vídeos curtos são um jeito ótimo de chegar já no clima. Se é a sua primeira vez no Brasil, estes ajudam a preparar o terreno:',
        videos: [
          ['Dots on a Map — Brasília', 'https://www.youtube.com/watch?v=HbS_nmFAddk'],
          ['Dots on a Map — Rio de Janeiro', 'https://www.youtube.com/watch?v=3FioV9MwBOA'],
          ['Dots on a Map — Salvador', 'https://www.youtube.com/watch?v=53qpaG8Q2OA'],
          ['Dots on a Map — Florianópolis', 'https://www.youtube.com/watch?v=iS022g0kT9A'],
          ['Dots on a Map — São Paulo', 'https://www.youtube.com/watch?v=tvaXa7HS7ow'],
          ['Melhores lugares para visitar no Brasil', 'https://www.youtube.com/watch?v=q7zdJ-nMrlE'],
          ['O que turistas devem saber sobre o Brasil', 'https://www.youtube.com/watch?v=NXtnHGvhIQg'],
          ['Brasil em 2 semanas', 'https://www.youtube.com/watch?v=sremk7jo15k'],
          ['Frases que você precisa antes de viajar ao Brasil', 'https://www.youtube.com/watch?v=eMsDho6otek'],
        ] },
      info: [
        { icon: 'wifi', title: 'Internet (eSIM)', lead: 'Ficar online no Brasil é fácil e barato:', items: [
          ['O mais simples', 'é um eSIM de viagem comprado antes de embarcar. [Airalo](https://www.airalo.com) (cupom de desconto de $3: MATHEU7267), Holafly ou Saily ativam assim que você pousa — sem trocar o chip físico nem pagar roaming caro.'],
          ['Um chip local', 'da Vivo, Claro ou TIM é ainda mais barato, mas geralmente exige um CPF, que a maioria dos visitantes não tem.'],
          ['A cobertura', 'é excelente em todas as grandes cidades, e o Wi-Fi é comum em hotéis, restaurantes e shoppings — é só pedir a senha.'],
          ['Dica:', 'dados móveis são essenciais aqui — você vai precisar para Uber, mapas e tradução.'],
        ] },
        { icon: 'chat', title: 'Idioma', lead: 'O idioma é o português — uma língua própria, diferente do espanhol (embora o espanhol ajude a entender o básico).', items: [
          ['O inglês', 'não é amplamente falado fora de hotéis e pontos turísticos, então não conte com ele no dia a dia.'],
          ['O Google Tradutor', 'ajuda muito — os modos câmera e conversa são salvadores. Baixe o pacote de português offline por garantia.'],
          ['Não tenha vergonha:', 'os brasileiros são famosos pela simpatia e fazem questão de ajudar. Um “obrigado / obrigada” com um sorriso abre todas as portas.'],
        ] },
        { icon: 'money', title: 'Custo de vida', lead: 'Para a maioria dos visitantes internacionais, o Brasil tem ótimo custo-benefício:', items: [
          ['As passagens aéreas', 'são o maior gasto — os preços internacionais subiram com o petróleo, então reserve o quanto antes.'],
          ['O resto', '— comida, transporte e lazer — é bem mais barato que nos EUA ou na Europa. Uma boa refeição ou um Uber longo não pesam no bolso.'],
          ['O dia a dia', 'é simples: cartões são aceitos em todo lugar e o câmbio é favorável (cerca de R$5 ≈ US$1).'],
        ] },
        { icon: 'sun', title: 'Clima', lead: 'Prepare-se para o calor. O fim de dezembro é pleno verão no Brasil — para quem foge do inverno do norte, o contraste é grande.', items: [
          ['Brasília e o Sul/Sudeste:', 'quente, úmido e em plena estação chuvosa — dias claros cortados por pancadas rápidas e fortes à tarde. É comum simplesmente esperar a chuva passar.'],
          ['O Nordeste:', 'quente e bem mais seco — clima perfeito de praia.'],
          ['O Norte (Amazônia):', 'quente e úmido o ano todo, com pouca variação.'],
          ['Em todo lugar:', 'protetor solar, chapéu, roupas leves e uma garrafa de água são seus melhores amigos.'],
        ] },
        { icon: 'health', title: 'Saúde & vacinas', lead: 'Algumas dicas práticas de saúde para a viagem:', items: [
          ['Vacinas', 'Nenhuma vacina é _exigida_ para entrar no Brasil, mas algumas são _recomendadas_ dependendo de para onde você vai. Veja o [aviso de saúde do CDC](https://wwwnc.cdc.gov/travel/destinations/traveler/none/brazil) e do [Reino Unido](https://www.gov.uk/foreign-travel-advice/brazil/print) para a orientação mais recente.'],
          ['Água da torneira', 'Não beba água da torneira em nenhum lugar do Brasil — prefira água mineral ou filtrada. A maioria das casas, hotéis e restaurantes tem um filtro que você pode usar.'],
        ] },
        { icon: 'shield', title: 'Segurança', lead: 'O Brasil é muito acolhedor, mas um pouco de atenção ajuda para quem vem de países bem mais seguros:', items: [
          ['Não chame atenção.', 'Evite exibir joias, relógios ou o celular na rua — use o telefone dentro de lojas ou restaurantes.'],
          ['Cuidado com os lugares.', 'Prefira áreas movimentadas, iluminadas e turísticas, e evite ruas vazias. Pergunte ao hotel quais bairros evitar, e **nunca** visite favelas.'],
          ['Separe o essencial.', 'Leve uma cópia da página de foto do passaporte e deixe o original no hotel; leve dois cartões e deixe um guardado.'],
          ['Fique de olho nos seus pertences.', 'Não deixe bolsas, celulares ou câmeras sem atenção — na praia, na mesa, em qualquer lugar.'],
          ['Atravessar a rua.', 'Brasília é uma das raras cidades brasileiras onde os carros param para o pedestre; em quase todo o resto do país eles costumam _não_ parar — nem na faixa. Atravesse com cuidado e prefira os semáforos.'],
          ['Aviso de viagem.', 'Para a orientação oficial mais recente, veja os guias do [Reino Unido](https://www.gov.uk/foreign-travel-advice/brazil/print) e do [Departamento de Estado dos EUA](https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/brazil-travel-advisory.html) sobre o Brasil.'],
        ], foot: 'Nada disso deve te deixar ansioso — fale com a gente se tiver qualquer dúvida ou preocupação!' },
      ],
      biomes: { title: 'Os biomas do Brasil', lead: 'O Brasil é de escala continental, e a paisagem muda completamente de uma região para outra. São seis grandes biomas:', items: [
        { name: 'Amazônia', desc: 'A maior floresta tropical do mundo: densa, úmida e cheia de vida.', img: '/images/biome-amazonia.webp' },
        { name: 'Mata Atlântica', desc: 'A floresta exuberante do litoral, que abraça cidades como Rio e São Paulo.', img: '/images/biome-mata-atlantica.webp' },
        { name: 'Cerrado', desc: 'A savana tropical ao redor de Brasília: árvores retorcidas, céus enormes e biodiversidade surpreendente.', img: '/images/biome-cerrado.webp' },
        { name: 'Pantanal', desc: 'A maior área úmida tropical do planeta, e o melhor lugar do Brasil para ver animais.', img: '/images/biome-pantanal.webp' },
        { name: 'Caatinga', desc: 'O sertão semiárido do Nordeste, que não existe em nenhum outro lugar do mundo.', img: '/images/biome-caatinga.webp' },
        { name: 'Pampas', desc: 'Os campos do extremo Sul, terra dos gaúchos.', img: '/images/biome-pampas.webp' },
      ] },
      food: { title: 'Comida', lead: 'Venha com fome. A cozinha brasileira é generosa, regional e feita para compartilhar:', foot: 'O Brasil tem um repertório surpreendentemente grande de opções sem glúten.', items: [
        { name: 'Churrasco', desc: 'A brasa brasileira, com cortes de carne sem fim.', img: '/images/food-churrasco.webp' },
        { name: 'Feijoada', desc: 'O prato nacional: um ensopado encorpado de feijão-preto e porco, melhor num almoço longo e tranquilo, com cerveja gelada e música ao vivo.', img: '/images/food-feijoada.webp' },
        { name: 'Farofa', desc: 'Farinha de mandioca torrada, a companhia crocante de quase tudo.', img: '/images/food-farofa.webp' },
        { name: 'Moqueca', desc: 'Um ensopado de peixe perfumado com leite de coco, tomate e azeite de dendê.', img: '/images/food-moqueca.webp' },
        { name: 'Acarajé', desc: 'Comida de rua baiana de origem nigeriana, cheia de sabor.', img: '/images/food-acaraje.webp' },
        { name: 'Pão de queijo', desc: 'Quentinho e elástico; impossível comer só um.', img: '/images/food-pao-de-queijo.webp' },
        { name: 'Coxinha', desc: 'O salgado em formato de gota, rei dos petiscos.', img: '/images/food-coxinha.webp' },
        { name: 'Açaí', desc: 'A tigela gelada da fruta amazônica, servida bem grossa.', img: '/images/food-acai.webp' },
        { name: 'Tapioca', desc: 'Crepes de mandioca, doces ou salgados.', img: '/images/food-tapioca.webp' },
        { name: 'Brigadeiro', desc: 'O doce clássico de qualquer festa.', img: '/images/food-brigadeiro.webp' },
        { name: 'Pudim', desc: 'Flan no melhor estilo brasileiro.', img: '/images/food-pudim.webp' },
        { name: 'Caipirinha', desc: 'O coquetel nacional: cachaça, limão, açúcar e gelo.', img: '/images/food-caipirinha.webp' },
      ] },
      holidays: { title: 'Natal & Réveillon', lead: 'Nosso casamento cai bem entre os dois maiores feriados do Brasil, então vale saber como o país comemora:', items: [
        { name: 'Natal (24–25 de dez)', desc: 'Uma celebração familiar e calorosa — a comemoração principal é a ceia na noite do dia 24, e a maioria das lojas e restaurantes fecha nos dias 24 e 25.', img: '/images/holiday-christmas.webp' },
        { name: 'Réveillon (Ano Novo)', desc: 'Uma festa nacional, melhor à beira-mar: vista branco e pule sete ondas à meia-noite. As maiores festas são no Rio, em Florianópolis, Salvador e Recife. Os hotéis esgotam cedo, então reserve com antecedência.', img: '/images/holiday-new-years-eve.webp' },
      ] },
      music: { title: 'Música & dança', lead: 'A música está em todo lugar no Brasil, e cada região tem seu próprio ritmo:', foot: 'Não se preocupe se você não sabe dançar — até o fim da noite, você vai saber.', items: [
        { name: 'Samba', desc: 'O coração do Rio e do Carnaval. Fique de olho em [rodas de samba](https://www.youtube.com/watch?v=wGaWVuBIyGY) na praia e [samba de gafieira](https://youtu.be/S7ExdpVmVBw?si=exTOyiG768jRxEWf&t=65) em festas. Outros sub-gêneros importantes incluem [pagode](https://www.youtube.com/watch?v=c4XeTP11EI8) e [samba-enredo](https://www.youtube.com/watch?v=PEcYx_Tljbo) (do desfile de Carnaval do Rio de Janeiro, conhecido mundialmente).', img: '/images/music-samba.webp' },
        { name: 'Forró', desc: 'Ritmo de sanfona e percursão típico do Nordeste. O [forró](https://www.youtube.com/watch?v=RacuiR1vpKg) é o ritmo mais popular para dança a dois em todo o Brasil. Confira também outros gêneros como [xote](https://www.youtube.com/watch?v=QDAHMMMtFBI), [baião](https://www.youtube.com/watch?v=ZeZ0B36sy1c) e [xaxado](https://www.youtube.com/watch?v=G8GADCfpavU).', img: '/images/music-forro.webp' },
        { name: 'Olodum & axé', desc: 'Ritmos percussivos e cheios de energia da Bahia. [Olodum](https://www.youtube.com/watch?v=A3o30YJiWsc), tocado por um conjunto de percursão com forte influência africana, pode ser escutado nas ruas de Salvador. [Axé](https://www.youtube.com/watch?v=xNo2kP7HJyw) é o ritmo do Carnaval da Bahia. Confira também o [maracatu](https://www.youtube.com/watch?v=DqZX8m2T-e0), outro gênero percursivo originado em Pernambuco.', img: '/images/music-olodum.webp' },
        { name: 'Sertanejo', desc: 'A música do interior e, atualmente, o gênero mais popular do país com forte inspiração da música country e mariachi. Confira alguns dos sub-gêneros como a tradicional [moda de viola](https://www.youtube.com/watch?v=JSFj3UGaO3Y), [sertanejo universitário](https://www.youtube.com/watch?v=rS2FDyOKR2g) e [agronejo](https://www.youtube.com/watch?v=vBPuW9IerfU).', img: '/images/music-sertanejo.webp' },
        { name: 'Funk', desc: 'Ritmo urbano e dançante do Rio de Janeiro e São Paulo, recebeu muita influência do Hip Hop, Miami Bass e Freestyle. Sub-gêneros incluem [funk carioca](https://www.youtube.com/watch?v=am3U2a_wpV4), [funk ostentação](https://www.youtube.com/watch?v=V1sRhopUw44), [funk melody](https://www.youtube.com/watch?v=PVV5qQl_HDo), [ravefunk](https://www.youtube.com/watch?v=SmpNmsuNA2E), [trapfunk](https://www.youtube.com/watch?v=aHBW_Nd_z8k) e [eletrofunk](https://www.youtube.com/watch?v=7CF5qbw8zec).', img: '/images/music-funk.webp' },
        { name: 'Choro', desc: 'O primeiro gênero popular urbano do Brasil: [ápido, virtuoso e instrumental](https://www.youtube.com/watch?v=fgrGb5cx2SA), nasceu no Rio do século 19 ao misturar [música de câmara europeia](https://www.youtube.com/watch?v=kdLKTDsm3EA), [percursão africana](https://www.youtube.com/watch?v=wA9tUYS4sc4) e [ritmos indígenas](https://www.youtube.com/watch?v=9RUO1E5AS0M). Típicamente tocado por [músicos em roda](https://www.youtube.com/watch?v=WLT6AkL8U7U), o choro é [frequentemente instrumental](https://www.youtube.com/watch?v=PusYdptMjXM) e contém [muita improvisação](https://www.youtube.com/watch?v=pn2FlgUfMM4) por músicos virtuosos [tal qual no Jazz](https://www.youtube.com/watch?v=RWXqlJ0Zydc). Não deixe de conferir o [Clube do Choro de Brasília](https://www.youtube.com/watch?v=rHcRes2wUpo) e assista a alguns dos melhores músicos do país ao vivo!', img: '/images/music-choro.webp' },
      ] },
      trip: { title: 'Aproveite a viagem',
        lead: 'Brasília fica no centro do país, com conexões rápidas para o litoral e além. Se você vai voar até aqui, vale conhecer mais do Brasil.',
        items: [
          { name: 'Rio de Janeiro', desc: 'Praias, Cristo Redentor e Pão de Açúcar — o cartão-postal do Brasil.', img: '/images/rio de janeiro.webp' },
          { name: 'São Paulo', desc: 'A maior cidade do Brasil: gastronomia, arte e vida noturna de primeira.', img: '/images/sao paulo.webp' },
          { name: 'Belo Horizonte', desc: 'A capital de Minas Gerais — botecos lendários e porta de entrada para as cidades históricas.', img: '/images/travel-belo-horizonte.webp' },
          { name: 'Salvador', desc: 'O coração afro-brasileiro da Bahia: cor, história e ritmo.', img: '/images/salvador.webp' },
          { name: 'Recife', desc: 'Capital histórica do Nordeste, ao lado da colorida Olinda.', img: '/images/travel-recife.webp' },
          { name: 'Florianópolis', desc: 'Uma ilha com mais de 40 praias e lagoas — queridinha do Réveillon.', img: '/images/travel-florianopolis.webp' },
          { name: 'Manaus & Floresta Amazônica', desc: 'Passeios de barco e hotéis na maior floresta tropical do mundo.', img: '/images/amazonia.webp' },
          { name: 'Foz do Iguaçu', desc: 'Uma das maiores cataratas do mundo, na fronteira com a Argentina.', img: '/images/foz do iguacu.webp' },
          { name: 'Lençóis Maranhenses', desc: 'Dunas brancas sem fim salpicadas de lagoas de água da chuva.', img: '/images/lencois maranhenses.webp' },
          { name: 'Fernando de Noronha', desc: 'Um arquipélago protegido com as praias mais lindas do Brasil.', img: '/images/fernando de noronha.webp' },
          { name: 'Chapada dos Veadeiros', desc: 'O maior parque nacional do Cerrado — pertinho de Brasília.', img: '/images/chapada dos veadeiros.webp' },
          { name: 'Porto de Galinhas', desc: 'Piscinas naturais quentes e praias protegidas por recifes, em Pernambuco.', img: '/images/porto de galinhas.webp' },
          { name: 'Búzios, Cabo Frio & Arraial do Cabo', desc: 'Vilas de praia charmosas e água turquesa perto do Rio.', img: '/images/buzios.webp' },
          { name: 'Ouro Preto', desc: 'Joia colonial barroca nas montanhas de Minas — Patrimônio Mundial da UNESCO.', img: '/images/travel-ouro-preto.webp' },
          { name: 'Paraty', desc: 'Cidade colonial entre a floresta e o mar.', img: '/images/paraty.webp' },
          { name: 'Pirenópolis', desc: 'Uma cidade colonial na serra, com cachoeiras, a poucas horas de Brasília.', img: '/images/travel-pirenopolis.webp' },
          { name: 'Jericoacoara', desc: 'Uma vila isolada de dunas e praias no Ceará, famosa pelo pôr do sol.', img: '/images/travel-jericoacoara.webp' },
        ] } },
    brasilia: { eyebrow: 'A cidade onde você vai pousar', title: 'Brasília', photo: 'brasília · skyline modernista',
      whatTitle: 'Uma obra de arte modernista',
      intro: '[A capital do Brasil](https://pt.wikipedia.org/wiki/Brasília) foi construída no cerrado e inaugurada em 1960 — uma cidade modernista imaginada pelo urbanista [Lúcio Costa](https://pt.wikipedia.org/wiki/Lúcio_Costa) e pelo arquiteto [Oscar Niemeyer](https://pt.wikipedia.org/wiki/Oscar_Niemeyer), desenhada em forma de avião. Seus marcos de concreto e vidro lhe renderam o título de Patrimônio Mundial da UNESCO — não existe lugar igual.',
      seeLabel: 'O que ver e fazer',
      sights: [
        { name: 'Catedral de Brasília', desc: 'A coroa de vidro e luz de Niemeyer. [Esta catedral deslumbrante](https://en.wikipedia.org/wiki/Cathedral_of_Brasília) é circular e exibe anjos suspensos, feitos de concreto, contra vitrais belíssimos. Imperdível!', img: '/images/brasilia-catedral.webp' },
        { name: 'Congresso Nacional', desc: 'As torres gêmeas e as cúpulas na Esplanada dos Ministérios; abriga a [Câmara dos Deputados e o Senado](https://en.wikipedia.org/wiki/National_Congress_Palace). Quem conhece a [sede da ONU](https://en.wikipedia.org/wiki/Headquarters_of_the_United_Nations) em Nova York vai notar semelhanças — afinal, o prédio da ONU foi projetado pelo mesmo Oscar Niemeyer e seu mentor, Le Corbusier.', img: '/images/brasilia-congresso.webp' },
        { name: 'Palácio do Planalto', desc: 'O [gabinete do presidente](https://en.wikipedia.org/wiki/Palácio_do_Planalto), todo em vidro e curvas. O prédio parece flutuar, com suas colunas curvas tocando o chão de leve.', img: '/images/brasilia-palacio-do-planalto.webp' },
        { name: 'Supremo Tribunal Federal', desc: 'A [mais alta corte do país](https://en.wikipedia.org/wiki/Supreme_Federal_Court), na [Praça dos Três Poderes](https://en.wikipedia.org/wiki/Praça_dos_Três_Poderes): uma única praça que reúne as sedes dos três poderes.', img: '/images/brasilia-stf.webp' },
        { name: 'Palácio do Itamaraty', desc: 'O [Ministério das Relações Exteriores](https://en.wikipedia.org/wiki/Itamaraty_Palace), com jardins de água e arcos. Projetado por Oscar Niemeyer e com paisagismo de [Burle Marx](https://en.wikipedia.org/wiki/Roberto_Burle_Marx), é talvez o ápice do modernismo brasileiro. Não deixe de ver a icônica escada em espiral e o jardim no terraço. [Agende sua visita com antecedência aqui](https://www.gov.br/mre/pt-br/assuntos/palacio-itamaraty/visite-o-itamaraty).', img: '/images/brasilia-itamaraty.webp' },
        { name: 'Palácio da Justiça', desc: 'O [Ministério da Justiça](https://pt.wikipedia.org/wiki/Palácio_da_Justiça_%28Brasília%29), em frente ao Palácio do Itamaraty, exibe impressionantes cascatas em estilo brutalista e plantas tropicais. A fusão perfeita do artificial com o natural.', img: '/images/brasilia-palacio-da-justica.webp' },
        { name: 'Museu da República', desc: 'Um [museu futurista](https://museu.cultura.df.gov.br/#) com mostras temporárias de arte moderna.', img: '/images/brasilia-museu-da-republica.webp' },
        { name: 'Teatro Nacional', desc: 'Um teatro modernista, casa da Orquestra Sinfônica de Brasília.', img: '/images/brasilia-teatro-nacional.webp' },
        { name: 'Ponte JK', desc: 'A elegante ponte de três arcos sobre o Lago Paranoá. Atravesse de carro ou jante em um dos muitos restaurantes à beira do lago.', img: '/images/brasilia-ponte-jk.webp' },
        { name: 'Torre de TV', desc: 'Um [mirante gratuito](https://www.turismo.df.gov.br/torre-de-tv/) com vista ampla da cidade. Curta um belo pôr do sol enquanto come no café lá em cima.', img: '/images/brasilia-torre-de-tv.webp' },
        { name: 'Torre Digital', desc: 'A torre "flor" de Niemeyer, com [um mirante panorâmico](https://www.df.gov.br/torre-de-tv-digital/) no alto de uma colina, de onde se vê todo o Distrito Federal.', img: '/images/brasilia-torre-digital.webp' },
        { name: 'Universidade de Brasília', desc: 'O campus de uma das melhores universidades do país, unindo brutalismo e natureza. Conheça o [Instituto Central de Ciências](https://maps.app.goo.gl/rkCkYQx7wBSSbZK16) — um único prédio de mais de 1 km —, a [Reitoria](https://maps.app.goo.gl/P3zY4sVgM367zozX8) e a [Biblioteca Central](https://maps.app.goo.gl/nyGXCDhmuLux7eQD8).', img: '/images/brasilia-unb.webp' },
        { name: 'Santuário Dom Bosco', desc: 'Uma [capela](https://maps.app.goo.gl/LEvtQtT7rkzFs4aH8) marcada por vitrais azuis do chão ao teto em todos os lados e um enorme lustre de Murano. Visite num dia ensolarado para o efeito máximo.', img: '/images/brasilia-santuario-dom-bosco.webp' },
        { name: 'Pontão do Lago Sul', desc: '[Point animado](https://maps.app.goo.gl/sE4ezYVh1ZBDwMrm8) à beira do Lago Paranoá, com calçadas ladeadas de palmeiras, cafés e vista para a Ponte JK. Ótimo para um passeio no fim da tarde ou um jantar.', img: '/images/brasilia-pontao.webp' },
        { name: 'Igrejinha', desc: 'Uma pequena [capela católica](https://maps.app.goo.gl/ZRRZgki4CQETXazw8) moderna, com azulejos de [Athos Bulcão](https://en.wikipedia.org/wiki/Athos_Bulcão), uma marca de Brasília.', img: '/images/brasilia-igrejinha.webp' },
        { name: 'Parque da Cidade', desc: 'Um [enorme parque urbano](https://maps.app.goo.gl/RhupSgqhwkunHuVZ9) para caminhar, pedalar, se exercitar e fazer piquenique. Ótimo para correr no fim da tarde, seguido de água de coco gelada e açaí. Use protetor solar e leve os óculos de sol: o sol aqui é forte!', img: '/images/brasilia-parque-da-cidade.webp' },
        { name: 'Praça dos Cristais', desc: 'Ampla [praça triangular](https://maps.app.goo.gl/VUWktsmKB3qNAWYB6) assinada por [Burle Marx](https://en.wikipedia.org/wiki/Roberto_Burle_Marx), com esculturas, espelhos d\'água e caminhos. Fica em frente ao quartel-general das Forças Armadas.', img: '/images/brasilia-praca-dos-cristais.webp' },
        { name: 'Parque Olhos d\'Água', desc: 'Um pequeno parque de vizinhança, com bastante natureza, trilhas sombreadas para caminhar e correr, e um lago com fauna local. Queridinho da vizinhança!', img: '/images/brasilia-parque-olhos-dagua.webp' },
        { name: 'Lago Paranoá', desc: 'O lago da cidade — passeios ao pôr do sol, caiaque e stand-up paddle.', img: '/images/brasilia-lago-paranoa.webp' },
        { name: 'Água Mineral', desc: '[Uma reserva florestal dentro da cidade](https://maps.app.goo.gl/tkkPoLZDbp3N2kDg8), com trilhas e uma piscina pública. Viva o Cerrado sem sair de Brasília.', img: '/images/brasilia-agua-mineral.webp' },
        { name: 'Ermida Dom Bosco', desc: '[Um mirante natural](https://maps.app.goo.gl/dDHUF9K82CLYVbk68) com um pôr do sol espetacular. Um tesouro escondido.', img: '/images/brasilia-ermida-dom-bosco.webp' },
        { name: 'Eixão do lazer', desc: 'Esporte, cultura e comida no [principal eixo da cidade](https://maps.app.goo.gl/xpMQ9ubn2Ljg5a7p8), fechado para carros aos domingos e feriados.', img: '/images/brasilia-eixao-do-lazer.webp' },
        { name: 'Salto do Itiquira', desc: 'Uma reserva florestal [perto de Brasília](https://maps.app.goo.gl/TscCAXqMmpka4EpK8) com uma das mais altas cachoeiras do país.', img: '/images/brasilia-salto-do-itiquira.webp' },
        { name: 'Chapada dos Veadeiros', desc: '[Cachoeiras e cânions](https://maps.app.goo.gl/59vTM4SqYKoGPCfCA) a ~3h de Brasília — um bate-volta pelo cerrado.', img: '/images/chapada dos veadeiros.webp' },
        { name: 'Pirenópolis', desc: 'Uma [cidade colonial na serra](https://maps.app.goo.gl/RMaiLHaJb7khMB5j8) com cachoeiras, a ~2h da capital.', img: '/images/brasilia-pirenopolis.webp' },
      ],
      eatLabel: 'Onde comer e beber',
      eatLead: 'Brasília tem centenas de cafés, bares e restaurantes charmosos. Estes são alguns dos nossos favoritos!',
      eat: [
        { name: 'Ernesto Café', desc: '[Café sofisticado e intimista](https://maps.app.goo.gl/LpNoy9LYwLgr8CMh8) para quem ama livros, com bebidas quentes e petiscos.', img: '/images/brasilia-coffee-shops.webp' },
        { name: 'Mangai', desc: 'Um farto bufê de comida nordestina — conforto regional de verdade.', img: '' },
        { name: 'Coco Bambu', desc: 'Frutos do mar em porções generosas, um sucesso garantido.', img: '' },
        { name: 'Beirute', desc: 'Uma instituição de Brasília na Asa Sul: um bar-restaurante animado, ótimo para cerveja gelada e petiscos.', img: '' },
        { name: 'Bar Brasília', desc: 'Um boteco clássico, com chope e comida de bar tradicional.', img: '' },
        { name: 'Clube do Choro', desc: 'Choro ao vivo, com drinques e petiscos.', img: '' },
      ] },
    rsvp: { eyebrow: 'Confirmação · responda até setembro de 2026', title: 'Você vem?',
      intro: 'Vamos manter a celebração intimista. Conte para a gente se poderá vir.',
      notes: [
        ['Apenas adultos', 'Por mais que a gente ame as crianças, esta será uma noite para os adultos.'],
        ['Sem acompanhantes extras', 'O convite é para os nomes nele indicados. Se tiver dúvida sobre quem está incluído, é só perguntar.'],
        ['Responda até setembro de 2026', 'Assim conseguimos confirmar os números finais com o espaço.'],
      ],
      name: 'Nome completo', namePh: 'Seu nome', email: 'E-mail', emailPh: 'voce@email.com',
      attending: 'Você vai?', attendingPh: 'Escolha…', yes: 'Sim, com alegria', no: 'Infelizmente, não',
      guests: 'Convidados', note: 'Recado ou pedido de música', notePh: 'Opcional…',
      submit: 'Enviar confirmação', sending: 'Enviando…', soon: 'Em breve',
      thanks: 'Obrigado — sua confirmação foi registrada!', thanksBody: 'Mal podemos esperar para celebrar com você.',
      error: 'Algo deu errado. Tente novamente ou escreva para matheus@matheusportela.com.',
      foot: 'Sabemos que vir até aqui é um compromisso de verdade, e não levamos isso por menos. Obrigado por fazer o esforço de celebrar conosco!' },
    registry: { eyebrow: 'Lista de presentes', title: 'Presentes',
      intro: 'Sua presença — especialmente para quem vem de longe — já é o único presente que esperamos. Como moramos fora, por favor não se preocupe em trazer nada físico. Mas, se quiser nos ajudar com a futura lua de mel, uma contribuição é muito bem-vinda.',
      ways: [['Pix', 'Transferências no Brasil\n(Reais)', 'E-mail:', 'btg@matheusportela.com'], ['Venmo', 'Transferências nos EUA\n(Dólares)', 'Usuário:\n(últimos 4 dígitos do telefone: 7457)', '@matheusportela'], ['Zelle', 'Transferências nos EUA\n(Dólares)', 'E-mail:', 'matheus@matheusportela.com'], ['Europa', 'Transferências na Europa\n(Euros)', 'IBAN:', '**Nome:** MATHEUS VIEIRA PORTELA\n**IBAN:** BE22 9672 4991 8947\n**SWIFT/BIC:** TRWIBEB1XXX\n**Nome e endereço do banco:**\nWise, Rue du Trône 110, 3rd floor, Brussels, 1050, Belgium'], ['Wise', 'Transferências internacionais\n(todas as moedas)', 'Usuário:', '@matheusv65'], ['Outros', '', 'Se quiser nos presentear mas não conseguir usar nenhum dos métodos acima, é só falar com a gente!']],
      note: 'Nenhum presente é esperado. De verdade!' },
    footer: { dateLine: '29 · 12 · 2026 — Brasília, Brasil' },
  },
};
