// content.js — all guest-facing text, in English (en) and Brazilian Portuguese (pt).
// This is the file to edit when updating names, dates, descriptions, gift handles, etc.
export const I18N = {
  en: {
    code: 'en',
    nav: { inicio: 'Home', evento: 'The Wedding', padrinhos: 'Our People', viagem: 'Travel', cidade: 'Brazil', rsvp: 'RSVP', presentes: 'Gifts', confirmar: 'RSVP' },
    hero: { eyebrow: 'We’re getting married · Brasília, Brazil', dateItalic: 'Tuesday, the twenty-ninth of December, two thousand twenty-six',
      chips: ['29 Dec 2026', '4 PM · Ceremony', 'Espaço Renascença'] },
    couple: { eyebrow: 'The couple', title: 'Welcome',
      p1: 'We’re so happy you’re here. After years of shared coffees, long trips and a life built between two countries, we’re finally throwing the party — and we want you in it.',
      p2: 'This little site has everything you need: the day itself, how to reach Brasília, what to see while you’re in Brazil, and how to say yes. Take your time and explore.' },
    party: { eyebrow: 'Those who walk with us', title: 'Our People', namePh: 'Name Surname',
      intro: 'The people who shaped our story and will stand beside us on the day. (Names below are placeholders — send us the final list.)',
      groups: [
        { group: 'Honour Attendants', people: [['Name Surname', 'Maid of Honour'], ['Name Surname', 'Best Man']] },
        { group: 'Bridesmaids', people: [['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid'], ['Name Surname', 'Bridesmaid']] },
        { group: 'Groomsmen', people: [['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman'], ['Name Surname', 'Groomsman']] },
      ] },
    event: { eyebrow: 'The big day', title: 'The Wedding',
      intro: 'An open-air ceremony followed by dinner and dancing, in a green hideaway minutes from central Brasília.',
      ceremony: { tag: 'Ceremony', time: '4 PM', desc: 'In the open garden, beneath the timber frame. Arrive from 3:30 PM for a cold coconut water.' },
      reception: { tag: 'Reception', time: '6 PM', desc: 'Dinner, toasts and a dance floor in the hall next door — until dawn, for those who last.' },
      rows: [['Location', 'Espaço Renascença\nRua das Acácias, s/n · Brasília — DF'], ['Dress code', 'Cocktail / dressy. Open-air garden — light fabrics.'], ['Weather', 'Tropical summer: 22–30 °C, with a chance of a quick shower late afternoon.']],
      mapBtn: 'View on map' },
    travel: { eyebrow: 'For our guests, especially from abroad', title: 'Travel',
      intro: 'Everything you need to plan the trip to Brasília — getting here, getting around, and the practical bits.',
      cards: [
        ['Getting to Brasília', 'Fly into Brasília–Juscelino Kubitschek International Airport (BSB), Brazil’s third-largest hub.', ['Direct international: TAP from Lisbon (~9h10), GOL from Miami & Orlando, Copa from Panama City.', 'From elsewhere, connect via São Paulo–Guarulhos (GRU) — the main long-haul gateway.', 'Domestic carriers: LATAM, GOL and Azul fly to BSB from across Brazil.']],
        ['Getting around', 'Brasília was designed for cars, so distances between sights are large.', ['Uber & 99 are reliable, inexpensive and the easiest way to move — we recommend them.', 'Airport to the central hotel sectors is ~13 km / 20 minutes.', 'Renting a car is optional; parking is plentiful and free in most places.']],
        ['Where to stay', 'Most hotels sit in the central Setor Hoteleiro (Sul & Norte), 15–20 min from the venue.', ['Higher end: B Hotel · Brasília Palace (Niemeyer landmark on the lake).', 'Comfortable: Cullinan · Allia Gran · Meliá.', 'We’ll share a group block & code closer to the date.']],
        ['Money & currency', 'The currency is the Brazilian Real (R$ / BRL). Roughly R$5 ≈ US$1 (rates vary).', ['Cards are accepted almost everywhere; contactless is standard.', 'PIX (instant bank transfer) is used for nearly everything locally.', 'Tell your bank you’re travelling; ATMs: Banco do Brasil, Bradesco, Santander.']],
        ['Visa & entry', 'Requirements changed in 2025 — please check early.', ['US, Canada & Australia: e-Visa required (in force since Apr 2025). Apply at the official portal brazil.vfsevisa.com — about US$80.90, 2–3 weeks ahead.', 'UK & EU: no visa for tourism up to 90 days.', 'Passport valid 6+ months. Always confirm with official government sources.']],
        ['When to book', 'Late December is peak Brazilian summer and holiday season — plan ahead.', ['Flights: book 4–6 months out for the best fares.', 'Hotels: reserve early; the city fills around New Year.', 'e-Visa: apply at least 3 weeks before departure.']],
      ] },
    newyear: { eyebrow: 'Make a holiday of it', title: 'Réveillon in Brazil', photo: 'réveillon · fireworks on the beach',
      p: ['Our wedding lands two days before New Year’s Eve — the perfect excuse to stay and celebrate ', 'Réveillon', ', Brazil’s biggest party. Tradition says: dress in white for peace, jump seven waves at midnight, and watch fireworks light up the coast.'],
      places: [['Rio de Janeiro', 'Copacabana beach — ~2 million in white, fireworks over the bay. ~1h45 flight from Brasília.'], ['Florianópolis & Búzios', 'Beach-town glamour and all-night parties on the southern and Rio coasts.'], ['Salvador & São Paulo', 'Afro-Brazilian rhythm on the beach, or Av. Paulista’s street celebration.']] },
    city: { eyebrow: 'Where you’re headed', title: 'Brasília & Brazil', photo: 'brasília · modernist skyline',
      intro: 'A little about the city — and the country — for those visiting Brazil for the first time.',
      whatTitle: 'What is Brasília?',
      whatP: 'Brazil’s capital was built from open savanna and inaugurated in 1960 — a modernist city imagined by urban planner Lúcio Costa and architect Oscar Niemeyer, laid out in the shape of an aeroplane. Its sweeping concrete-and-glass landmarks earned it UNESCO World Heritage status, and it’s unlike anywhere else on earth.',
      seeLabel: 'Things to see & do',
      sights: [['Cathedral of Brasília', 'Niemeyer’s crown of light'], ['National Congress', 'The twin towers & domes'], ['Praça dos Três Poderes', 'Heart of the capital'], ['JK Memorial', 'The city’s founder'], ['Itamaraty Palace', 'Water gardens & arches'], ['Pontão do Lago Sul', 'Sunset dining by the lake']],
      foodTitle: 'Food & culture', foodP: 'Come hungry: sizzling churrasco, warm pão de queijo, brigadeiros and ice-cold caipirinhas. Expect easy warmth, live music, and a table that never seems to empty.',
      tripTitle: 'Make it a trip', tripP: 'Brasília sits at the centre of the country, with quick connections to the coast and beyond. If you’re flying this far, it’s worth seeing more of Brazil.',
      beyondLabel: 'Beyond Brasília',
      brazil: [['Rio de Janeiro', 'Beaches, Christ the Redeemer, Sugarloaf'], ['Foz do Iguaçu', 'One of the world’s great waterfalls'], ['Salvador & Bahia', 'Afro-Brazilian culture and colour'], ['Amazon · Manaus', 'Rainforest and river journeys'], ['Fernando de Noronha', 'Brazil’s most beautiful islands'], ['São Paulo', 'Gastronomy and big-city energy']] },
    rsvp: { eyebrow: 'RSVP · please reply by 30 Nov 2026', title: 'Will you come?',
      intro: 'Let us know if you can celebrate with us. One form per guest or family is perfect.',
      name: 'Full name', namePh: 'Your name', email: 'Email', emailPh: 'you@email.com',
      attending: 'Attending?', attendingPh: 'Joyfully yes / Sadly no', guests: 'Guests',
      note: 'A note or song request', notePh: 'Optional…', submit: 'Send RSVP' },
    registry: { eyebrow: 'Gift list', title: 'Gifts',
      intro: 'Since we live abroad, please — no physical gifts. Your presence is truly the gift. If you’d like to help us start this next chapter, a contribution is warmly welcomed.',
      ways: [['Pix', 'For guests in Brazil', 'Instant transfer — our PIX key:', 'annaematheus@email.com'], ['Wise', 'For international guests', 'Send in your currency, low fees:', 'wise.com/pay/annaematheus'], ['Venmo', 'For guests in the US', 'Quick and easy:', '@anna-matheus']],
      note: 'Handles above are placeholders — we’ll add the real keys before launch.' },
    footer: { dateLine: '29 · 12 · 2026 — Brasília, Brazil' },
  },

  pt: {
    code: 'pt',
    nav: { inicio: 'Início', evento: 'O Evento', padrinhos: 'Padrinhos', viagem: 'Viagem', cidade: 'Brasília', rsvp: 'RSVP', presentes: 'Presentes', confirmar: 'Confirmar' },
    hero: { eyebrow: 'Nós vamos casar · Brasília, Brasil', dateItalic: 'terça-feira, vinte e nove de dezembro de dois mil e vinte e seis',
      chips: ['29 Dez 2026', '16h · Cerimônia', 'Espaço Renascença'] },
    couple: { eyebrow: 'O casal', title: 'Bem-vindos',
      p1: 'Que alegria ter você aqui. Depois de anos de cafés compartilhados, viagens longas e uma vida construída entre dois países, vamos finalmente fazer a festa — e queremos você nela.',
      p2: 'Este site tem tudo o que você precisa: o grande dia, como chegar a Brasília, o que ver pelo Brasil e como confirmar presença. Fique à vontade para explorar.' },
    party: { eyebrow: 'Quem caminha conosco', title: 'Padrinhos', namePh: 'Nome Sobrenome',
      intro: 'As pessoas que fizeram parte da nossa história e estarão ao nosso lado no grande dia. (Os nomes abaixo são exemplos — envie a lista final.)',
      groups: [
        { group: 'Padrinhos de Honra', people: [['Nome Sobrenome', 'Madrinha de Honra'], ['Nome Sobrenome', 'Padrinho de Honra']] },
        { group: 'Madrinhas', people: [['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha'], ['Nome Sobrenome', 'Madrinha']] },
        { group: 'Padrinhos', people: [['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho'], ['Nome Sobrenome', 'Padrinho']] },
      ] },
    event: { eyebrow: 'O grande dia', title: 'O Evento',
      intro: 'Uma cerimônia ao ar livre seguida de festa, num refúgio verde a poucos minutos do centro de Brasília.',
      ceremony: { tag: 'Cerimônia', time: '16h00', desc: 'No jardim aberto, sob a estrutura de madeira. Chegue a partir das 15h30 para um copo de água de coco gelada.' },
      reception: { tag: 'Recepção', time: '18h00', desc: 'Jantar, brindes e pista de dança no salão ao lado — até o amanhecer, para quem aguentar.' },
      rows: [['Local', 'Espaço Renascença\nRua das Acácias, s/n · Brasília — DF'], ['Traje', 'Esporte fino / cocktail. Jardim ao ar livre — tecidos leves.'], ['Clima', 'Verão tropical: 22–30 °C, com possibilidade de chuva rápida no fim da tarde.']],
      mapBtn: 'Ver no mapa' },
    travel: { eyebrow: 'Para nossos convidados, especialmente de fora', title: 'Viagem',
      intro: 'Tudo o que você precisa para planejar a viagem a Brasília — como chegar, como se locomover e os detalhes práticos.',
      cards: [
        ['Como chegar a Brasília', 'Voe até o Aeroporto Internacional de Brasília–Juscelino Kubitschek (BSB), o terceiro maior do Brasil.', ['Voos diretos internacionais: TAP de Lisboa (~9h10), GOL de Miami e Orlando, Copa do Panamá.', 'De outros lugares, conecte por São Paulo–Guarulhos (GRU), o principal portão internacional.', 'Companhias domésticas: LATAM, GOL e Azul voam para BSB de todo o Brasil.']],
        ['Como se locomover', 'Brasília foi feita para carros, então as distâncias entre os pontos são grandes.', ['Uber e 99 são confiáveis, baratos e o jeito mais fácil de circular — recomendamos.', 'Do aeroporto aos setores hoteleiros centrais são ~13 km / 20 minutos.', 'Alugar carro é opcional; estacionamento é abundante e gratuito na maioria dos lugares.']],
        ['Onde ficar', 'A maioria dos hotéis fica no Setor Hoteleiro central (Sul e Norte), 15–20 min do local.', ['Mais sofisticado: B Hotel · Brasília Palace (marco de Niemeyer à beira do lago).', 'Confortável: Cullinan · Allia Gran · Meliá.', 'Vamos compartilhar um bloco e código de grupo mais perto da data.']],
        ['Dinheiro & moeda', 'A moeda é o Real (R$ / BRL). Aproximadamente R$5 ≈ US$1 (varia).', ['Cartões são aceitos em quase todo lugar; aproximação é padrão.', 'O PIX (transferência instantânea) é usado para quase tudo por aqui.', 'Avise seu banco da viagem; caixas: Banco do Brasil, Bradesco, Santander.']],
        ['Visto & entrada', 'As regras mudaram em 2025 — verifique com antecedência.', ['EUA, Canadá e Austrália: e-Visa obrigatório (em vigor desde abr/2025). Solicite no portal oficial brazil.vfsevisa.com — cerca de US$80,90, com 2–3 semanas de antecedência.', 'Reino Unido e UE: sem visto para turismo até 90 dias.', 'Passaporte válido por 6+ meses. Sempre confirme em fontes oficiais.']],
        ['Quando reservar', 'O fim de dezembro é alta temporada de verão e festas — planeje com antecedência.', ['Voos: reserve com 4–6 meses para os melhores preços.', 'Hotéis: reserve cedo; a cidade lota perto do Ano Novo.', 'e-Visa: solicite ao menos 3 semanas antes de viajar.']],
      ] },
    newyear: { eyebrow: 'Aproveite e fique', title: 'Réveillon no Brasil', photo: 'réveillon · fogos na praia',
      p: ['Nosso casamento é dois dias antes do Ano Novo — a desculpa perfeita para ficar e celebrar o ', 'Réveillon', ', a maior festa do Brasil. A tradição manda: vestir branco pela paz, pular sete ondas à meia-noite e ver os fogos iluminarem a costa.'],
      places: [['Rio de Janeiro', 'Praia de Copacabana — ~2 milhões de branco, fogos sobre a baía. ~1h45 de voo de Brasília.'], ['Florianópolis & Búzios', 'Glamour litorâneo e festas a noite toda no Sul e na costa do Rio.'], ['Salvador & São Paulo', 'Ritmo afro-brasileiro na praia, ou a festa de rua da Av. Paulista.']] },
    city: { eyebrow: 'Para onde você vai', title: 'Brasília & Brasil', photo: 'brasília · skyline modernista',
      intro: 'Um pouco sobre a cidade — e o país — para quem visita o Brasil pela primeira vez.',
      whatTitle: 'O que é Brasília?',
      whatP: 'A capital do Brasil foi construída no cerrado e inaugurada em 1960 — uma cidade modernista imaginada pelo urbanista Lúcio Costa e pelo arquiteto Oscar Niemeyer, desenhada em forma de avião. Seus marcos de concreto e vidro lhe renderam o título de Patrimônio Mundial da UNESCO — não existe lugar igual.',
      seeLabel: 'O que ver e fazer',
      sights: [['Catedral de Brasília', 'A coroa de luz de Niemeyer'], ['Congresso Nacional', 'As torres e cúpulas'], ['Praça dos Três Poderes', 'O coração da capital'], ['Memorial JK', 'O fundador da cidade'], ['Palácio do Itamaraty', 'Jardins de água e arcos'], ['Pontão do Lago Sul', 'Jantar ao pôr do sol no lago']],
      foodTitle: 'Comida & cultura', foodP: 'Venha com fome: churrasco na brasa, pão de queijo quentinho, brigadeiros e caipirinhas geladas. Espere calor humano, música ao vivo e uma mesa que nunca esvazia.',
      tripTitle: 'Aproveite a viagem', tripP: 'Brasília fica no centro do país, com conexões rápidas para o litoral e além. Se vai voar até aqui, vale conhecer mais do Brasil.',
      beyondLabel: 'Além de Brasília',
      brazil: [['Rio de Janeiro', 'Praias, Cristo Redentor, Pão de Açúcar'], ['Foz do Iguaçu', 'Uma das grandes cataratas do mundo'], ['Salvador & Bahia', 'Cultura e cor afro-brasileiras'], ['Amazônia · Manaus', 'Floresta e viagens pelos rios'], ['Fernando de Noronha', 'As ilhas mais lindas do Brasil'], ['São Paulo', 'Gastronomia e energia de metrópole']] },
    rsvp: { eyebrow: 'Confirmação · responda até 30 nov 2026', title: 'Você vem?',
      intro: 'Conte para a gente se poderá celebrar conosco. Um formulário por convidado ou família é perfeito.',
      name: 'Nome completo', namePh: 'Seu nome', email: 'E-mail', emailPh: 'voce@email.com',
      attending: 'Você vai?', attendingPh: 'Sim, com alegria / Infelizmente não', guests: 'Convidados',
      note: 'Recado ou pedido de música', notePh: 'Opcional…', submit: 'Enviar confirmação' },
    registry: { eyebrow: 'Lista de presentes', title: 'Presentes',
      intro: 'Como moramos fora, por favor — nada de presentes físicos. Sua presença já é o maior presente. Mas, se quiser nos ajudar a começar este novo capítulo, uma contribuição é muito bem-vinda.',
      ways: [['Pix', 'Para convidados no Brasil', 'Transferência instantânea — nossa chave PIX:', 'annaematheus@email.com'], ['Wise', 'Para convidados internacionais', 'Envie na sua moeda, com taxas baixas:', 'wise.com/pay/annaematheus'], ['Venmo', 'Para convidados nos EUA', 'Rápido e fácil:', '@anna-matheus']],
      note: 'Os contatos acima são exemplos — colocaremos as chaves reais antes do lançamento.' },
    footer: { dateLine: '29 · 12 · 2026 — Brasília, Brasil' },
  },
};
